import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);const root=document.getElementById("accountPage");
const AV={leaf:"🍃",book:"📖",star:"✦",cloud:"☁",moon:"☾",sun:"☀",flower:"✿",mountain:"⌁",wave:"〰",cat:"◕ᴥ◕",fox:"🦊",owl:"🦉"};
const EMOJIS=["😀","😎","🥹","😂","🥰","🤓","🧐","😴","🤍","🩵","🩷","💜","🧡","💛","💚","🌱","🌿","🌸","🌻","🍀","🌙","⭐","☁️","🌈","🦊","🐱","🐶","🐼","🐻","🐰","🦉","🐸","🐳","🦋","🐝","🍓","🍒","🍋","🍉","🍪","🧋","☕","🎧","📷","🎨","🎵","🎮","⚽","✈️","💎","🔥","🌊"];
const ROLE={member:"成员",subject_manager:"学科负责人",coordinator:"Coordinator"};let session,profile,manages=[];
const esc=s=>String(s??"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[m]));
const toast=m=>{const t=document.getElementById("toast");if(!t)return;t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
const avatarHtml=p=>p?.avatar_url?`<img src="${esc(p.avatar_url)}" alt="头像">`:(p?.avatar_emoji||AV[p?.avatar_key]||AV.leaf);
async function save(p){const {data,error}=await sb.rpc("update_my_profile",p);if(error){const m=error.message||"";toast(m.includes("username")?"这个昵称已经被使用":"保存失败，请稍后再试");return null}if(!data){toast("保存失败：没有收到更新后的资料");return null}profile={...profile,...data};return data}
async function refreshProfile(){const r=await sb.from("profiles").select("*").eq("id",session.user.id).maybeSingle();if(!r.error&&r.data)profile=r.data;manages=(await sb.from("subject_managers").select("subject_id,subjects(name,code)").eq("user_id",session.user.id)).data||[]}
async function load(){const {data:{session:s}}=await sb.auth.getSession();session=s;if(!session){location.replace("./auth.html");return}await refreshProfile();if(window.EpistemeI18n&&profile?.language)await window.EpistemeI18n.setLanguage(profile.language,false);render()}
function render(){const p=profile||{};root.innerHTML=`<div class="account-wrap account-v3"><div class="account-intro"><div class="eyebrow">MY ACCOUNT</div><h1>个人资料</h1><p>管理你的昵称、头像、语言、身份和账号状态。</p></div><div class="account-layout-v3"><aside class="account-profile"><div class="profile-avatar">${avatarHtml(p)}<button class="avatar-camera" id="avatarCamera" title="上传图片">⌁</button></div><h2>${esc(p.username||"成员")}</h2><div class="username">${esc(session.user.email||"")}</div><span class="role-pill">${ROLE[p.role]||"成员"}</span><div class="profile-subjects">${p.role==="coordinator"?`<span>全部 ${manages.length||16} 个学科</span>`:manages.map(x=>`<span>${esc(x.subjects?.name||"学科")}</span>`).join("")}</div><button class="account-button primary full" id="home">进入知屿 →</button></aside><div class="account-main"><section class="account-card profile-editor"><h3>个人资料</h3><p class="sub">昵称会显示在 Question Card、回答和讨论中。</p><div class="field"><label>昵称</label><div class="inline"><input id="name" value="${esc(p.username||"")}" maxlength="30"><button class="account-button primary" id="save">保存</button></div></div><div class="field"><label>头像</label><div class="avatar-tools"><button class="avatar-tool active" id="emojiMode">选择 Emoji</button><button class="avatar-tool" id="uploadMode">上传图片</button></div><div id="emojiPanel" class="emoji-panel">${EMOJIS.map(e=>`<button class="emoji-choice ${p.avatar_emoji===e&&!p.avatar_url?"selected":""}" data-emoji="${esc(e)}">${e}</button>`).join("")}</div><input id="avatarFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden><div class="avatar-upload-note">支持 JPG / PNG / WEBP / GIF，单张最大 5 MB。</div></div><div class="field"><label>语言偏好</label><div class="language-buttons"><button class="lang-btn ${p.language!=="en"?"selected":""}" data-lang="zh-CN">简体中文</button><button class="lang-btn ${p.language==="en"?"selected":""}" data-lang="en">English</button></div></div></section><section class="account-card"><h3>身份与邀请码</h3><p class="sub">输入新的邀请码，获得对应角色或学科权限。</p><div class="identity-box"><div><small>当前角色</small><b>${ROLE[p.role]||"成员"}</b></div><div><small>学科权限</small><b>${p.role==="coordinator"?"全部 16 个学科":`${manages.length} 个学科`}</b></div></div><form class="invite-form" id="invite"><input name="code" autocomplete="off" placeholder="输入邀请码"><button class="account-button primary">验证并升级</button></form><div class="invite-result" id="result"></div></section><section class="account-card"><h3>账号管理</h3><div class="account-actions-grid"><button class="account-button" id="switch">切换账号</button><button class="account-button danger" id="out">退出登录</button></div></section></div></div>`;bind()}
function bind(){document.getElementById("home").onclick=()=>location.replace("./");document.getElementById("save").onclick=async()=>{const name=document.getElementById("name").value.trim();if(!name){toast("昵称不能为空");return}const d=await save({p_username:name});if(d){document.querySelector(".account-profile h2").textContent=profile.username;document.getElementById("name").value=profile.username;toast("昵称已更新")}};document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=async()=>{const lang=b.dataset.lang;const d=await save({p_language:lang});if(d){localStorage.setItem("episteme-language",lang);localStorage.setItem("episteme_language",lang);if(window.EpistemeI18n)await window.EpistemeI18n.setLanguage(lang,false);document.querySelectorAll("[data-lang]").forEach(x=>x.classList.toggle("selected",x.dataset.lang===profile.language));toast(lang==="en"?"Language preference saved":"语言偏好已保存")}});document.querySelectorAll("[data-emoji]").forEach(b=>b.onclick=async()=>{const d=await save({p_avatar_key:"leaf",p_avatar_emoji:b.dataset.emoji,p_avatar_url:""});if(d){render();toast("头像已更新")}});document.getElementById("emojiMode").onclick=()=>{document.getElementById("emojiPanel").style.display="grid"};document.getElementById("uploadMode").onclick=()=>document.getElementById("avatarFile").click();document.getElementById("avatarCamera").onclick=()=>document.getElementById("avatarFile").click();document.getElementById("avatarFile").onchange=uploadImage;document.getElementById("invite").onsubmit=claim;document.getElementById("switch").onclick=async()=>{await sb.auth.signOut();location.replace("./auth.html")};document.getElementById("out").onclick=async()=>{await sb.auth.signOut();location.replace("./")}}
async function uploadImage(e){const file=e.target.files?.[0];if(!file)return;if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type)){toast("请选择 JPG、PNG、WEBP 或 GIF 图片");return}if(file.size>5*1024*1024){toast("图片不能超过 5 MB");return}const ext=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;toast("正在上传头像……");const {error}=await sb.storage.from("episteme-avatars").upload(path,file,{upsert:false,contentType:file.type});if(error){toast("头像上传失败："+error.message);return}const {data}=sb.storage.from("episteme-avatars").getPublicUrl(path);const saved=await save({p_avatar_key:"leaf",p_avatar_emoji:"",p_avatar_url:data.publicUrl});if(saved){render();toast("头像已更新")}}
async function claim(e){e.preventDefault();const code=String(new FormData(e.target).get("code")||"").trim(),out=document.getElementById("result"),btn=e.target.querySelector("button");if(!code){out.textContent="请输入邀请码。";return}btn.disabled=true;btn.textContent="验证中……";const {data,error}=await sb.rpc("claim_subject_manager_invite",{p_code:code});if(error){out.textContent="邀请码无效、已失效，或暂未开放。";btn.disabled=false;btn.textContent="验证并升级";return}await refreshProfile();render();toast(data?.role==="coordinator"?"升级成功！你现在是 Coordinator。":"升级成功！你的学科权限已更新。")}
load();