import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);const root=document.getElementById("accountPage");
const AV={leaf:"🍃",book:"📖",star:"✦",cloud:"☁",moon:"☾",sun:"☀",flower:"✿",mountain:"⌁",wave:"〰",cat:"◕ᴥ◕",fox:"🦊",owl:"🦉"};const ROLE={member:"成员",subject_manager:"学科负责人",coordinator:"coordinator"};let session,profile,manages=[];
const esc=s=>String(s||"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[m]));const toast=m=>{const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
async function save(p){const {data,error}=await sb.rpc("update_my_profile",p);if(error){toast(error.message.includes("username already")?"这个昵称已经被使用":"保存失败，请稍后再试");return null}profile=data;return data}
async function load(){const {data:{session:s}}=await sb.auth.getSession();session=s;if(!session){location.replace("./auth.html");return}profile=(await sb.from("profiles").select("*").eq("id",session.user.id).maybeSingle()).data;manages=(await sb.from("subject_managers").select("subject_id,subjects(name,code)").eq("user_id",session.user.id)).data||[];render()}
function render(){const av=AV[profile?.avatar_key]||AV.leaf;root.innerHTML=`<div class="account-wrap"><div class="account-intro" style="text-align:left"><div class="eyebrow">MY ACCOUNT</div><h1>账号管理</h1><p>管理昵称、头像、语言、邀请码和登录状态。</p></div><div class="account-grid"><aside class="account-profile"><div class="account-avatar">${av}</div><h2>${esc(profile?.username||"成员")}</h2><div class="username">${esc(session.user.email||"")}</div><span class="role-pill">${ROLE[profile?.role]||"成员"}</span>${manages.length?`<div class="subject-list">${manages.map(x=>`<span>${esc(x.subjects?.name||"学科")}</span>`).join("")}</div>`:""}<button class="account-button" id="home" style="width:100%;margin-top:22px">进入知屿 →</button></aside><div class="account-main"><section class="account-card"><h3>个人资料</h3><p class="sub">你的 Question Card、回答和讨论会使用这些资料。</p><div class="settings-row"><div><b>昵称</b><small>公开名称</small></div><div style="display:flex;gap:7px"><input id="name" value="${esc(profile?.username||"")}" maxlength="30" style="flex:1;border:1px solid var(--line);border-radius:10px;padding:10px;font-size:11px"><button class="account-button primary" id="save">保存</button></div></div><div class="settings-row"><div><b>头像</b><small>点击即可更换</small></div><div class="avatar-mini-grid">${Object.entries(AV).map(([k,v])=>`<button class="avatar-mini ${k===(profile?.avatar_key||"leaf")?"selected":""}" data-av="${k}">${v}</button>`).join("")}</div></div><div class="settings-row"><div><b>语言</b><small>界面偏好</small></div><div class="language-buttons"><button class="lang-btn ${profile?.language!=="en"?"selected":""}" data-lang="zh-CN">简体中文</button><button class="lang-btn ${profile?.language==="en"?"selected":""}" data-lang="en">English</button></div></div></section><section class="account-card"><h3>身份与邀请码</h3><p class="sub">输入新的邀请码，获得对应角色或学科权限。</p><form class="invite-form" id="invite"><input name="code" autocomplete="off" placeholder="输入邀请码"><button class="account-button primary">验证并升级</button></form><div class="invite-result" id="result"></div></section><section class="account-card"><h3>账号操作</h3><p class="sub">退出后可以立即登录另一个账号。</p><div class="danger-actions"><button class="account-button" id="switch">切换账号</button><button class="account-button danger" id="out">退出当前账号</button></div></section></div></div>`;bind()}
function bind(){document.getElementById("home").onclick=()=>location.replace("./");document.querySelectorAll("[data-av]").forEach(b=>b.onclick=async()=>{if(await save({p_avatar_key:b.dataset.av})){render();toast("头像已更新")}});document.getElementById("save").onclick=async()=>{const name=document.getElementById("name").value.trim();if(await save({p_username:name})){render();toast("昵称已更新")}};document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=async()=>{if(await save({p_language:b.dataset.lang})){localStorage.setItem("episteme_language",b.dataset.lang);render();toast("语言偏好已保存")}});document.getElementById("invite").onsubmit=claim;document.getElementById("switch").onclick=async()=>{await sb.auth.signOut();location.replace("./auth.html")};document.getElementById("out").onclick=async()=>{await sb.auth.signOut();location.replace("./")}}
async function claim(e){e.preventDefault();const code=String(new FormData(e.target).get("code")||"").trim(),out=document.getElementById("result"),btn=e.target.querySelector("button");if(!code){out.textContent="请输入邀请码。";return}btn.disabled=true;btn.textContent="验证中……";const {error}=await sb.rpc("claim_subject_manager_invite",{p_code:code});if(error){out.textContent="邀请码无效、已失效，或暂未开放。";btn.disabled=false;btn.textContent="验证并升级";return}out.textContent="验证成功，权限正在更新……";setTimeout(load,600)}load();
