import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);const app=document.getElementById("app");let user=null,profile=null,subjects=[],resources=[],courses=[],lessons=[],questions=[],profiles=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function init(){const{data:{session}}=await sb.auth.getSession();user=session?.user||null;if(!user)return login();await load();if(!["admin","subject_manager"].includes(profile?.role))return denied();render()}
async function load(){profile=(await sb.from("profiles").select("*").eq("id",user.id).maybeSingle()).data;subjects=(await sb.from("subjects").select("*").order("name")).data||[];resources=(await sb.from("resources").select("*,subjects(name),profiles(username)").order("created_at",{ascending:false})).data||[];courses=(await sb.from("courses").select("*,subjects(name)").order("created_at",{ascending:false})).data||[];lessons=(await sb.from("course_lessons").select("*").order("lesson_order")).data||[];questions=(await sb.from("questions").select("*,subjects(name)").order("created_at",{ascending:false}).limit(40)).data||[];if(profile?.role==="admin")profiles=(await sb.from("profiles").select("id,username,role").order("created_at")).data||[]}
function login(){app.innerHTML='<section class="panel admin-login"><div class="eyebrow">EPISTEME</div><h1>后台登录</h1><p>使用 Episteme 账号登录。系统会自动检查你是否为学科负责人或管理员。</p><form id="loginForm"><input name="email" type="email" required placeholder="邮箱"><input name="password" type="password" required placeholder="密码"><button class="primary">登录</button></form></section>';document.getElementById("loginForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const r=await sb.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(r.error)toast(r.error.message);else location.reload()}}
function denied(){app.innerHTML='<section class="panel admin-login"><div class="eyebrow">ACCESS DENIED</div><h1>暂无后台权限</h1><p>请联系管理员把你的 profiles.role 设置为 subject_manager 或 admin。</p><a class="primary" href="./">返回网站</a></section>'}
function render(){const pending=resources.filter(r=>r.status!=="approved");app.innerHTML='<section class="page-hero"><div class="eyebrow">ADMIN / SUBJECT MANAGER</div><h1>后台管理</h1><p>资源审核、录课管理、问题状态与成员权限。</p></section><section class="admin-grid"><div class="panel"><div class="toolbar"><div><div class="eyebrow">RESOURCE REVIEW</div><h2>资源审核</h2></div><span>'+pending.length+' pending</span></div>'+resourceRows(pending)+'</div><div class="panel"><div class="toolbar"><div><div class="eyebrow">COURSES</div><h2>录课</h2></div><button class="primary" onclick="newCourse()">＋ 新课程</button></div>'+courseRows()+'</div><div class="panel"><div class="eyebrow">QUESTIONS</div><h2>问题状态</h2>'+questionRows()+'</div><div class="panel"><div class="eyebrow">PEOPLE</div><h2>成员权限</h2>'+peopleRows()+'</div></section>'}
function resourceRows(list){return list.length?list.map(r=>'<div class="admin-row"><div><b>'+esc(r.title)+'</b><small>'+esc(r.subjects?.name||"未分类")+' · '+r.status+'</small></div><div><button class="secondary" onclick="reviewResource(\''+r.id+'\',\'approved\')">通过</button> <button class="danger" onclick="reviewResource(\''+r.id+'\',\'rejected\')">驳回</button></div></div>').join(""):'<div class="empty">没有待审核资源。</div>'}
function courseRows(){return courses.length?courses.map(c=>'<div class="admin-row"><div><b>'+esc(c.title)+'</b><small>'+esc(c.subjects?.name||"未分类")+' · '+lessons.filter(l=>l.course_id===c.id).length+' 个章节</small></div><button class="secondary" onclick="newLesson(\''+c.id+'\')">＋ 章节</button></div>').join(""):'<div class="empty">暂无课程。</div>'}
function questionRows(){return questions.length?questions.map(q=>'<div class="admin-row"><div><b>'+esc(q.title)+'</b><small>'+esc(q.subjects?.name||"未分类")+'</small></div><select onchange="setQuestionStatus(\''+q.id+'\',this.value)"><option value="unanswered" '+(q.status==="unanswered"?"selected":"")+'>Unanswered</option><option value="discussing" '+(q.status==="discussing"?"selected":"")+'>Discussing</option><option value="answered" '+(q.status==="answered"?"selected":"")+'>Answered</option><option value="archived" '+(q.status==="archived"?"selected":"")+'>Archived</option></select></div>').join(""):'<div class="empty">暂无问题。</div>'}
function peopleRows(){if(profile?.role!=="admin")return'<div class="empty">只有 admin 可以修改成员角色。</div>';return profiles.map(p=>'<div class="admin-row"><div><b>'+esc(p.username||"Member")+'</b><small>'+esc(p.id)+'</small></div><select onchange="setRole(\''+p.id+'\',this.value)"><option value="student" '+(p.role==="student"?"selected":"")+'>student</option><option value="subject_manager" '+(p.role==="subject_manager"?"selected":"")+'>subject_manager</option><option value="admin" '+(p.role==="admin"?"selected":"")+'>admin</option></select></div>').join("")}
window.reviewResource=async(id,status)=>{const r=await sb.from("resources").update({status}).eq("id",id);if(r.error)toast(r.error.message);else{await load();render()}};
window.setQuestionStatus=async(id,status)=>{const r=await sb.from("questions").update({status}).eq("id",id);if(r.error)toast(r.error.message);else{await load();render()}};
window.setRole=async(id,role)=>{if(profile?.role!=="admin")return;const r=await sb.from("profiles").update({role}).eq("id",id);if(r.error)toast(r.error.message);else{await load();render()}};
window.newCourse=()=>modal("新建课程",'<form id="courseForm"><label>课程名称<input name="title" required placeholder="IGCSE Chemistry — Equilibrium"></label><label>学科<select name="subject">'+subjects.map(s=>'<option value="'+s.id+'">'+esc(s.name)+(s.code?" · "+esc(s.code):"")+'</option>').join("")+'</select></label><label>简介<textarea name="description"></textarea></label><button class="primary">创建课程</button></form>');
window.newLesson=id=>modal("添加章节",'<form id="lessonForm"><label>章节名称<input name="title" required placeholder="01 — Core Concepts"></label><label>视频链接<input name="video_url" type="url" placeholder="Bilibili / 其他公开视频链接"></label><label>顺序<input name="order" type="number" min="0" value="1"></label><label>时长（秒）<input name="duration" type="number" min="0" value="0"></label><button class="primary">保存章节</button></form>',async e=>{const f=new FormData(e.target);const r=await sb.from("course_lessons").insert({course_id:id,title:f.get("title"),video_url:f.get("video_url")||null,lesson_order:Number(f.get("order")||0),duration_seconds:Number(f.get("duration")||0)});if(r.error)toast(r.error.message);else{closeModal();await load();render()}});
function modal(title,body,after){document.getElementById("modal").innerHTML='<div class="backdrop"><div class="modal"><div class="modal-head"><h3>'+title+'</h3><button onclick="closeModal()">×</button></div>'+body+'</div></div>';const form=document.querySelector(".modal form");if(form)form.onsubmit=async e=>{e.preventDefault();if(after)return after(e);const f=new FormData(e.target);const r=await sb.from("courses").insert({title:f.get("title"),description:f.get("description"),subject_id:f.get("subject"),teacher_id:user.id});if(r.error)toast(r.error.message);else{closeModal();await load();render()}}}
window.closeModal=()=>document.getElementById("modal").innerHTML="";window.toast=m=>{const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
document.getElementById("signout").onclick=async()=>{await sb.auth.signOut();location.href="./"};init();