import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let user,profile,subjects=[],resources=[],managers=[],courses=[],lessons=[];let tab='resources';
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session){location.href='./#login';return}user=session.user;await loadProfile();if(!profile||!['coordinator','subject_manager'].includes(profile.role)){document.querySelector('#app').innerHTML='<div class="admin-card"><h2>没有后台权限</h2><p class="muted">只有 Coordinator 和 Subject Manager 可以进入这里。</p><a class="outline" href="./">返回网站</a></div>';return}await load();render()}
async function loadProfile(){let r=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();profile=r.data}
async function load(){const [s,r,m,c,l]=await Promise.all([sb.from('subjects').select('*').order('name'),sb.from('resources').select('*,subjects(name),profiles(username)').order('created_at',{ascending:false}),sb.from('subject_managers').select('*,profiles(username),subjects(name)').order('created_at',{ascending:false}),sb.from('courses').select('*,subjects(name)').order('created_at',{ascending:false}),sb.from('course_lessons').select('*').order('lesson_order')]);subjects=s.data||[];resources=r.data||[];managers=m.data||[];courses=c.data||[];lessons=l.data||[]}
const isCoord=()=>profile.role==='coordinator';
const managedIds=()=>managers.filter(m=>m.user_id===user.id).map(m=>Number(m.subject_id));
function visibleResources(){return isCoord()?resources:resources.filter(r=>managedIds().includes(Number(r.subject_id))||r.uploader_id===user.id)}
function visibleCourses(){return isCoord()?courses:courses.filter(c=>managedIds().includes(Number(c.subject_id)))}
function visibleSubjects(){return isCoord()?subjects:subjects.filter(s=>managedIds().includes(Number(s.id)))}
function render(){const title=isCoord()?'Coordinator 后台':'Subject Manager 后台';const tabs=isCoord()?['resources','managers','courses','subjects']:['resources','courses'];$('#app').innerHTML=`<div class="admin-top"><div><div class="eyebrow">EPISTEME · ADMIN</div><h1>${title}</h1><p>管理资料、课程与学科权限。所有写操作都由 Supabase RLS 再次校验。</p></div><span class="role-pill">${esc(profile.role)}</span></div><div class="admin-tabs">${tabs.map(x=>`<button class="admin-tab ${tab===x?'active':''}" data-tab="${x}">${label(x)}</button>`).join('')}</div><div id="view"></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});renderTab()}
const label=x=>({resources:'资料审核',managers:'Subject Manager',courses:'录课管理',subjects:'学科管理'})[x];
function renderTab(){const v=$('#view');if(tab==='resources')v.innerHTML=resourcesView();if(tab==='managers')v.innerHTML=managersView();if(tab==='courses')v.innerHTML=coursesView();if(tab==='subjects')v.innerHTML=subjectsView();bind()}
function resourcesView(){const rs=visibleResources(),pending=rs.filter(r=>r.status==='pending').length,approved=rs.filter(r=>r.status==='approved').length;return `<div class="stat-grid"><div class="stat"><b>${rs.length}</b><span class="muted">可管理资料</span></div><div class="stat"><b>${pending}</b><span class="muted">待审核</span></div><div class="stat"><b>${approved}</b><span class="muted">已通过</span></div></div><div class="admin-grid"><div class="admin-card"><h2>资料审核</h2><div class="section-note">成员上传后默认为 pending。Coordinator 管理全部资料；Subject Manager 只管理自己负责学科。</div><table class="admin-table"><thead><tr><th>资料</th><th>学科</th><th>上传者</th><th>状态</th><th>操作</th></tr></thead><tbody>${rs.length?rs.map(r=>`<tr><td><b>${esc(r.title)}</b><br><span class="muted">${esc(r.resource_type||r.category||'resource')}</span></td><td>${esc(r.subjects?.name||'未分类')}</td><td>${esc(r.profiles?.username||'成员')}</td><td>${statusText(r.status)}</td><td><div class="admin-actions"><button class="mini" data-view="${r.id}">查看</button>${r.status!=='approved'?`<button class="mini ok" data-approve="${r.id}">通过</button>`:''}${r.status!=='rejected'?`<button class="mini no" data-reject="${r.id}">拒绝</button>`:''}<button class="mini danger" data-delete="${r.id}">删除</button></div></td></tr>`).join(''):`<tr><td colspan="5">暂无资料</td></tr>`}</tbody></table></div><div class="admin-card"><h2>上传资料</h2>${uploadForm()}</div></div>`}
const statusText=s=>({pending:'待审核',approved:'已通过',rejected:'已拒绝'})[s]||s||'待审核';
function uploadForm(){return `<form id="uploadForm" class="form-grid"><label>资料标题<input name="title" required></label><label>学科<select name="subject_id" required><option value="">选择学科</option>${visibleSubjects().map(s=>`<option value="${s.id}">${esc(s.name)}${s.code?' · '+esc(s.code):''}</option>`).join('')}</select></label><label>Topic<input name="topic"></label><label>类型<select name="resource_type"><option value="notes">笔记</option><option value="worksheet">讲义</option><option value="past_paper">真题</option><option value="slides">Slides</option><option value="other">其他</option></select></label><label>描述<textarea name="description"></textarea></label><label>文件<input name="file" type="file" required></label><button class="primary" type="submit">上传并提交审核</button></form>`}
function managersView(){return `<div class="admin-grid"><div class="admin-card"><h2>Subject Managers</h2><div class="manager-list">${managers.length?managers.map(m=>`<div class="manager-row"><div><b>${esc(m.profiles?.username||m.user_id)}</b><small>${esc(m.subjects?.name||m.subject_id)}</small></div><button class="mini danger" data-manager-delete="${m.id}">移除</button></div>`).join(''):'<div class="empty-admin">还没有 Subject Manager</div>'}</div></div><div class="admin-card"><h2>分配负责人</h2><div class="section-note">填写用户 UUID，把某个学科交给 Subject Manager。重复分配会被数据库约束拦截。</div><form id="managerForm" class="form-grid"><label>User UUID<input name="user_id" required placeholder="profiles.id"></label><label>学科<select name="subject_id" required>${subjects.map(s=>`<option value="${s.id}">${esc(s.name)}${s.code?' · '+esc(s.code):''}</option>`).join('')}</select></label><button class="primary">分配 Subject Manager</button></form></div></div>`}
function coursesView(){const cs=visibleCourses();return `<div class="admin-grid"><div class="admin-card"><h2>现有录课</h2><table class="admin-table"><thead><tr><th>课程</th><th>学科</th><th>分类</th><th>Lessons</th></tr></thead><tbody>${cs.length?cs.map(c=>`<tr><td><b>${esc(c.title)}</b><br><span class="muted">${esc(c.description||'')}</span></td><td>${esc(c.subjects?.name||'未分类')}</td><td>${courseLabel(c.course_type)}</td><td>${lessons.filter(l=>l.course_id===c.id).length}</td></tr>`).join(''):'<tr><td colspan="4">暂无课程</td></tr>'}</tbody></table></div><div class="admin-card"><h2>创建录课</h2><div class="section-note">课程分为 <b>课本内容</b>、<b>IG 题目讲解</b>、<b>专题与进阶</b>。先创建课程，再添加 Lesson / 视频。</div><form id="courseForm" class="form-grid"><label>课程名称<input name="title" required></label><label>学科<select name="subject_id" required>${visibleSubjects().map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label>栏目<select name="course_type"><option value="textbook">课本内容</option><option value="ig">IG 题目讲解</option><option value="advanced">专题与进阶</option></select></label><label>简介<textarea name="description"></textarea></label><button class="primary">创建课程</button></form></div></div>`}
const courseLabel=x=>({textbook:'课本内容',ig:'IG 题目讲解',advanced:'专题与进阶'})[x]||x||'课本内容';
function subjectsView(){return `<div class="admin-card"><h2>学科</h2><table class="admin-table"><thead><tr><th>名称</th><th>Code</th><th>ID</th></tr></thead><tbody>${visibleSubjects().map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.code||'')}</td><td>${esc(s.id)}</td></tr>`).join('')}</tbody></table></div>`}
function bind(){document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>review(b.dataset.approve,'approved'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>review(b.dataset.reject,'rejected'));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeResource(b.dataset.delete));document.querySelectorAll('[data-manager-delete]').forEach(b=>b.onclick=()=>removeManager(b.dataset.managerDelete));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewResource(b.dataset.view));$('#uploadForm')?.addEventListener('submit',upload);$('#managerForm')?.addEventListener('submit',addManager);$('#courseForm')?.addEventListener('submit',addCourse)}
async function review(id,status){const r=resources.find(x=>x.id===id);if(!r)return;if(!isCoord()&&!managedIds().includes(Number(r.subject_id)))return alert('你没有管理这个学科的权限。');const update={status};if(status==='rejected'){const reason=prompt('请输入拒绝原因（可选）：');if(reason)update.rejection_reason=reason}const {error}=await sb.from('resources').update(update).eq('id',id);if(error)return alert(error.message);await load();render()}
async function removeResource(id){if(!confirm('确定删除这份资料？'))return;const r=resources.find(x=>x.id===id);if(!r)return;if(!isCoord()&&!managedIds().includes(Number(r.subject_id))&&! (r.uploader_id===user.id))return alert('你没有权限。');if(r.file_path)await sb.storage.from('episteme-resources').remove([r.file_path]);const {error}=await sb.from('resources').delete().eq('id',id);if(error)return alert(error.message);await load();render()}
async function viewResource(id){const r=resources.find(x=>x.id===id);if(!r)return;let url=r.external_url;if(r.file_path){const x=await sb.storage.from('episteme-resources').createSignedUrl(r.file_path,3600);url=x.data?.signedUrl}if(url)window.open(url,'_blank');else alert(`${r.title}\n\n${r.description||''}\n\n没有可访问链接`)}
async function upload(e){e.preventDefault();const f=new FormData(e.target),file=f.get('file');if(!file||!file.size)return alert('请选择文件。');const subjectId=Number(f.get('subject_id'));if(!isCoord()&&!managedIds().includes(subjectId))return alert('你只能上传到自己负责的学科。');const path=`${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let x=await sb.storage.from('episteme-resources').upload(path,file,{upsert:false});if(x.error)return alert(x.error.message);const row={title:f.get('title'),description:f.get('description'),subject_id:subjectId,topic:f.get('topic'),resource_type:f.get('resource_type'),file_path:path,uploader_id:user.id,status:'pending',file_size:file.size,mime_type:file.type||null};x=await sb.from('resources').insert(row);if(x.error){await sb.storage.from('episteme-resources').remove([path]);return alert(x.error.message)}alert('上传成功，已进入审核队列。');await load();render()}
async function addManager(e){e.preventDefault();if(!isCoord())return;const f=new FormData(e.target);const {error}=await sb.from('subject_managers').insert({user_id:f.get('user_id'),subject_id:Number(f.get('subject_id'))});if(error)return alert(error.message);await load();render()}
async function removeManager(id){if(!isCoord())return;const {error}=await sb.from('subject_managers').delete().eq('id',id);if(error)return alert(error.message);await load();render()}
async function addCourse(e){e.preventDefault();const f=new FormData(e.target),subjectId=Number(f.get('subject_id'));if(!isCoord()&&!managedIds().includes(subjectId))return alert('你只能管理自己负责的学科。');const {error}=await sb.from('courses').insert({title:f.get('title'),description:f.get('description'),subject_id:subjectId,teacher_id:user.id,course_type:f.get('course_type'),status:'published'});if(error)return alert(error.message);await load();render()}
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.href='./'};init();