import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const CFG=window.EPISTEME_CONFIG||{};
const configured=CFG.SUPABASE_URL && !CFG.SUPABASE_URL.includes("PASTE_") && CFG.SUPABASE_PUBLISHABLE_KEY && !CFG.SUPABASE_PUBLISHABLE_KEY.includes("PASTE_");
const supabase=configured?createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY):null;

const state={user:null,profile:null,subjects:[],questions:[],answers:[],courses:[],lessons:[],resources:[],messages:[],query:""};

const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const fmtDate=x=>new Date(x).toLocaleString("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"});
const route=()=>location.hash.slice(1)||"/";
function toast(m){const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),2300)}
function modal(title,body){document.getElementById("modalRoot").innerHTML=`<div class="backdrop" id="backdrop"><div class="modal"><div class="modal-head"><h3>${title}</h3><button onclick="closeModal()">×</button></div>${body}</div></div>`}
window.closeModal=()=>document.getElementById("modalRoot").innerHTML="";
const subjectName=id=>state.subjects.find(s=>s.id===id)?.name||"未分类";
const subjectId=name=>state.subjects.find(s=>s.name===name)?.id||null;
const statusText={unanswered:"Unanswered",discussing:"Discussing",answered:"Answered",archived:"Archived"};

async function boot(){
 if(!supabase){render();return}
 const {data:{session}}=await supabase.auth.getSession();
 await setUser(session?.user||null);
 supabase.auth.onAuthStateChange(async(_e,s)=>{await setUser(s?.user||null);});
 await loadAll();
 subscribeRealtime();
 render();
}
async function setUser(user){
 state.user=user;
 if(user){
   let {data}=await supabase.from("profiles").select("*").eq("id",user.id).maybeSingle();
   if(!data){await supabase.from("profiles").insert({id:user.id,username:user.email?.split("@")[0]||"New member"});({data}=await supabase.from("profiles").select("*").eq("id",user.id).maybeSingle())}
   state.profile=data;
 } else state.profile=null;
 updateAuthButton();
}
function updateAuthButton(){document.getElementById("authBtn").textContent=state.user?(state.profile?.username||"我的账号"):"登录 / 注册"}
async function loadAll(){
 const q=await supabase.from("questions").select("*,profiles(username),subjects(name)").order("created_at",{ascending:false});
 state.questions=q.data||[];
 const a=await supabase.from("answers").select("*,profiles(username)").order("created_at",{ascending:true});state.answers=a.data||[];
 const s=await supabase.from("subjects").select("*").order("name");state.subjects=s.data||[];
 const c=await supabase.from("courses").select("*,subjects(name),profiles(username)").order("created_at",{ascending:false});state.courses=c.data||[];
 const l=await supabase.from("course_lessons").select("*").order("lesson_order");state.lessons=l.data||[];
 const r=await supabase.from("resources").select("*,subjects(name),profiles(username)").order("created_at",{ascending:false});state.resources=r.data||[];
}
function subscribeRealtime(){
 supabase.channel("episteme-live")
 .on("postgres_changes",{event:"*",schema:"public",table:"questions"},async()=>{await loadAll();render()})
 .on("postgres_changes",{event:"*",schema:"public",table:"answers"},async()=>{await loadAll();if(route().startsWith("/question/")) render()})
 .on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},payload=>{if(payload.new.channel==="general"){state.messages.push(payload.new);if(route()==="/community")renderChat()}})
 .subscribe();
}
function navActive(){document.querySelectorAll("#nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+route()))}
function hero(k,t,d){return `<section class="page-hero"><div class="container page-hero-inner"><div class="eyebrow">${k}</div><h1>${t}</h1><p>${d}</p></div></section>`}
function home(){return `<section class="hero container"><div><div class="eyebrow">STUDENT-LED LEARNING COMMUNITY</div><h1>一起学习，<br>互相帮助，<br>让知识<strong>留下来。</strong></h1><p>Episteme 知屿是一个由高中生发起并主导的线上学习共同体。通过同伴授课、资源共享、答疑互助与 AI 辅助，我们希望让每一届学生都能给下一届留下更多知识。</p><div class="actions"><button class="primary" onclick="location.hash='#/community'">进入讨论群 →</button><button class="secondary" onclick="location.hash='#/library'">浏览资源库</button></div></div><div class="hero-art"><div class="sun"></div><div class="m1"></div><div class="m2"></div><div class="water"></div><div class="hero-logo"><img src="assets/logo.png"><b>Episteme 知屿</b><span>TRUE KNOWLEDGE BELONGS TO NO ONE.</span></div></div></section>
<section class="loop"><div class="container"><div class="section-head"><div class="eyebrow">THE KNOWLEDGE LOOP</div><h2>Ask → Discuss → Understand → Preserve → Share</h2></div><div class="loop-grid">${[["01","Ask","提出真实遇到的问题。"],["02","Discuss","进入对应学科共同思考。"],["03","Understand","关注逻辑，而不只是答案。"],["04","Preserve","高价值问答整理为长期知识。"],["05","Share","让下一位学习者继续使用。"]].map(x=>`<div><i>${x[0]}</i><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join("")}</div></div></section>
<section class="container spaces"><div class="section-head"><div class="eyebrow">EXPLORE</div><h2>知屿里的三个空间</h2></div><div class="space-grid"><a class="space sage" href="#/community"><small>COMMUNITY</small><h3>讨论群</h3><p>提问、回答、实时讨论，以及 Question Card。</p><span>进入讨论 →</span></a><a class="space blue" href="#/courses"><small>COURSES</small><h3>录课</h3><p>同伴授课，帮助理解概念、原理和知识之间的联系。</p><span>观看录课 →</span></a><a class="space lav" href="#/library"><small>LIBRARY</small><h3>资源库</h3><p>笔记、讲义、真题、工具和高价值知识长期保存。</p><span>浏览资源 →</span></a></div></section>
<section class="quote"><blockquote>“我们希望每一届学生离开时，都能给下一届留下比自己刚加入时更多的知识。”<cite>— EPISTEME 知屿</cite></blockquote></section>`}

function community(){
 if(!supabase)return setupNotice("COMMUNITY","讨论群","配置 Supabase 后，这里会自动变成真正的多人讨论区。");
 return hero("COMMUNITY","讨论群","Question Card + 实时讨论。高价值讨论可以进一步进入 Knowledge Base。")+`<section class="container content"><div class="community-grid"><aside class="panel"><div class="eyebrow">CHANNELS</div>${["全部","Mathematics","Physics","Chemistry","Biology","English","Economics","History","Geography","Theatre & Arts","Music"].map((s,i)=>`<button class="channel ${i===0?"active":""}" data-sub="${s}"># ${s}</button>`).join("")}</aside><div class="panel"><div class="toolbar"><div><div class="eyebrow">QUESTION CARDS</div><h2>${state.questions.length} 个问题</h2></div><button class="primary" onclick="ask()">＋ 提问</button></div><div class="filters">${["全部","unanswered","discussing","answered","archived"].map((s,i)=>`<button class="filter ${i===0?"active":""}" data-status="${s}">${i?statusText[s]:"全部"}</button>`).join("")}</div><div id="questions">${questionList()}</div></div></div><div class="panel chat-panel"><div class="toolbar"><div><div class="eyebrow">GENERAL CHAT</div><h2>开放讨论</h2></div>${state.user?`<span class="online">● 已登录</span>`:`<button class="secondary" onclick="auth()">登录后参与讨论</button>`}</div><div id="chat">${chatHtml()}</div>${state.user?`<form id="chatForm" class="chat-form"><input name="content" placeholder="说点什么……"><button class="primary">发送</button></form>`:`<div class="empty">登录后可以发送消息。</div>`}</div></section>`;
}
function questionList(sub="全部",st="全部",query=""){let list=state.questions.filter(q=>(sub==="全部"||subjectName(q.subject_id)===sub)&&(st==="全部"||q.status===st));if(query)list=list.filter(q=>(q.title+" "+q.content+" "+subjectName(q.subject_id)).toLowerCase().includes(query.toLowerCase()));return list.length?list.map(q=>`<article class="question" onclick="location.hash='#/question/${q.id}'"><div class="meta">${esc(q.profiles?.username||"成员")} · ${fmtDate(q.created_at)} <span class="badge">${esc(subjectName(q.subject_id))}</span><span class="status">${esc(statusText[q.status])}</span></div><h3>${esc(q.title)}</h3><p>${esc(q.content)}</p><div class="qfoot">${state.answers.filter(a=>a.question_id===q.id).length} 条回答 · 点击查看</div></article>`).join(""):`<div class="empty">没有找到符合条件的问题。</div>`}
function chatHtml(){return state.messages.length?state.messages.map(m=>`<div class="msg"><b>${esc(m.author_name||"成员")}</b><span>${fmtDate(m.created_at)}</span><p>${esc(m.content)}</p></div>`).join(""):`<div class="empty">还没有消息。登录后开始第一条讨论。</div>`}
function renderChat(){const el=document.getElementById("chat");if(el)el.innerHTML=chatHtml()}
async function loadChat(){if(!supabase||!state.user)return;const {data}=await supabase.from("messages").select("*,profiles(username)").eq("channel","general").order("created_at",{ascending:true}).limit(100);state.messages=(data||[]).map(m=>({...m,author_name:m.profiles?.username||"成员"}));renderChat()}
async function ask(){if(!state.user){auth();return}modal("提出一个问题",`<form class="form" id="askForm"><label>问题标题<input name="title" required placeholder="例如：为什么这道题答案是 C？"></label><label>学科<select name="subject">${state.subjects.map(s=>`<option value="${s.id}">${esc(s.name)} ${s.code?`· ${esc(s.code)}`:""}</option>`).join("")}</select></label><label>Topic<input name="topic" placeholder="例如：Trigonometry / Forces / Symbolism"></label><label>具体问题<textarea name="content" required placeholder="写下你的思路、卡住的地方，以及已经尝试过什么。"></textarea></label><p class="help">提交后会生成 Question Card。后续可以由 AI 做学科 / Topic 初步分类，再由学科负责人确认。</p><button class="submit">发布问题</button></form>`);document.getElementById("askForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.from("questions").insert({author_id:state.user.id,title:f.get("title"),content:f.get("content"),topic:f.get("topic"),subject_id:f.get("subject")});if(error)toast(error.message);else{closeModal();toast("Question Card 已创建");}}}
function questionDetail(id){const q=state.questions.find(x=>x.id===id);if(!q)return `<div class="empty">问题不存在。</div>`;const ans=state.answers.filter(a=>a.question_id===id);return hero("QUESTION CARD",q.title,`${subjectName(q.subject_id)} · ${statusText[q.status]} · ${fmtDate(q.created_at)}`)+`<section class="container content"><div class="panel detail"><a class="back" href="#/community">← 返回讨论</a><p class="detail-body">${esc(q.content)}</p><div class="divider"></div><h2>回答 · ${ans.length}</h2><div>${ans.length?ans.map(a=>`<div class="answer"><div class="meta">${esc(a.profiles?.username||"成员")} · ${fmtDate(a.created_at)} ${a.is_verified?`<span class="verified">✓ 已确认</span>`:""}</div><p>${esc(a.content)}</p></div>`).join(""):`<div class="empty">还没有回答，成为第一个帮助他人的人。</div>`}</div>${state.user?`<form id="answerForm" class="form"><textarea name="content" required placeholder="写下你的解释……"></textarea><button class="submit">提交回答</button></form>`:`<div class="admin-note">登录后可以回答问题。</div>`}</div></section>`}
function courseSectionFor(c){
 const raw=String(c.course_type||c.section||c.category||'').toLowerCase();
 const title=String(c.title||'').toLowerCase();
 if(raw.includes('textbook')||raw.includes('课本')||raw.includes('concept')) return 'textbook';
 if(raw.includes('ig')||raw.includes('题目')||raw.includes('exam')||raw.includes('past')) return 'ig';
 if(raw.includes('advanced')||raw.includes('专题')||raw.includes('拓展')||raw.includes('extension')) return 'advanced';
 if(title.includes('题目')||title.includes('past paper')||title.includes('exam')) return 'ig';
 return 'textbook';
}
const courseSectionMeta={
 textbook:{num:'01',eyebrow:'TEXTBOOK CONTENT',title:'课本内容',desc:'从课本出发，把概念、定义、公式和知识之间的逻辑讲清楚。'},
 ig:{num:'02',eyebrow:'IGCSE QUESTION WALKTHROUGH',title:'IG 题目讲解',desc:'不只讲答案，而是拆解题目、思路、常见错误与考试中的判断方式。'},
 advanced:{num:'03',eyebrow:'EXTENSION & TOPICS',title:'专题与进阶',desc:'课本之外的专题、小型探究与更深入的知识连接。'}
};
function courseCard(c){const type=courseSectionFor(c);return `<article class="card course-card" onclick="location.hash='#/course/${c.id}'"><div class="thumb ${type==='ig'?'blue':type==='advanced'?'lav':'sage'}"><span>${courseSectionMeta[type].num}</span><b>${esc(c.title)}</b></div><div class="card-body"><span class="badge">${esc(subjectName(c.subject_id))}</span><h3>${esc(c.title)}</h3><p>${esc(c.description||'暂无简介')}</p><div class="card-meta">${esc(c.profiles?.username||'Episteme')}</div></div></article>`}
function courses(){
 const sections=['textbook','ig','advanced'];
 return `<div class="courses-page">
  <section class="page-hero courses-hero"><div class="container page-hero-inner"><div class="eyebrow">COURSES · LEARN TO UNDERSTAND</div><h1>录课</h1><p>把同伴授课变成可以反复观看、跨年级留下来的学习内容。</p><div class="course-jump"><a href="#course-textbook">01 · 课本内容</a><a href="#course-ig">02 · IG 题目讲解</a><a href="#course-advanced">03 · 专题与进阶</a></div></div></section>
  ${sections.map(key=>{const m=courseSectionMeta[key];const list=state.courses.filter(c=>courseSectionFor(c)===key);return `<section class="course-section course-section-${key}" id="course-${key}"><div class="container course-section-grid"><div class="course-section-intro"><div class="course-number">${m.num}</div><div class="eyebrow">${m.eyebrow}</div><h2>${m.title}</h2><p>${m.desc}</p></div><div class="course-section-content">${list.length?`<div class="cards">${list.map(courseCard).join('')}</div>`:`<div class="course-empty"><span>${m.num}</span><div><b>这里会放${m.title}</b><p>学科负责人添加课程后，课程会自动出现在这里。</p></div></div>`}</div></div></section>`}).join('')}
 </div>`;
}
function courseDetail(id){const c=state.courses.find(x=>x.id===id);if(!c)return `<div class="container content"><div class="empty">课程不存在。</div></div>`;const ls=state.lessons.filter(x=>x.course_id===id);const type=courseSectionFor(c);return `<div class="course-detail-page"><section class="page-hero course-detail-hero"><div class="container page-hero-inner"><div class="eyebrow">${courseSectionMeta[type].eyebrow}</div><div class="course-detail-top"><span class="course-number">${courseSectionMeta[type].num}</span><div><h1>${esc(c.title)}</h1><p>${esc(subjectName(c.subject_id))} · ${esc(c.profiles?.username||'Episteme')}</p></div></div></div></section><section class="container content"><div class="panel course-player-panel"><a class="back" href="#/courses">← 返回录课</a><div class="viewer"><div><video id="player" class="video" controls ${ls[0]?.video_url?`src="${esc(ls[0].video_url)}"`:''}></video>${!ls[0]?.video_url?`<div class="video-empty">课程视频链接尚未添加</div>`:''}<div class="course-info"><b>课程简介</b><p>${esc(c.description||'暂无简介')}</p></div></div><div class="lessons"><div class="eyebrow">LESSONS</div>${ls.length?ls.map((l,i)=>`<button class="lesson ${i===0?'active':''}" onclick="playLesson('${l.id}',this)"><span>${String(i+1).padStart(2,'0')} · ${esc(l.title)}</span><small>${l.duration_seconds?Math.round(l.duration_seconds/60)+' min':'○'}</small></button>`).join(''):`<div class="empty">还没有章节。</div>`}</div></div></div></section></div>`}
window.playLesson=(id,btn)=>{const l=state.lessons.find(x=>x.id===id);document.querySelectorAll('.lesson').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const v=document.getElementById('player');if(l?.video_url&&v){v.src=l.video_url;v.play().catch(()=>{})}else toast('这一章节还没有视频链接')}
function resourceStatusLabel(status){return status==='approved'?'✓ 已审核':status==='pending'?'等待审核':'未通过审核'}
function resourceTypeLabel(type){return ({note:'笔记',paper:'真题',handout:'讲义',tool:'工具',other:'其他'})[type]||type||'资料'}
function canManageResources(){return !!state.user&&['subject_manager','admin'].includes(state.profile?.role)}
function library(){return `<div class="library-page"><section class="page-hero library-hero"><div class="container page-hero-inner"><div class="eyebrow">RESOURCE LIBRARY · SHARE & PRESERVE</div><h1>资源库</h1><p>查找、阅读和共享学习资料。社区成员可以上传，学科负责人负责审核与整理。</p><div class="library-actions"><button class="primary" onclick="uploadResource()">＋ 上传资料</button>${canManageResources()?`<a class="secondary manager-link" href="#/admin/resources">学科负责人后台 →</a>`:''}</div></div></section><section class="container content"><div class="library-toolbar"><div class="filters"><button class="filter active" data-resource-type="all">全部</button><button class="filter" data-resource-type="note">笔记</button><button class="filter" data-resource-type="paper">真题</button><button class="filter" data-resource-type="handout">讲义</button><button class="filter" data-resource-type="tool">工具</button><button class="filter" data-resource-type="other">其他</button></div><input class="searchbox" id="resSearch" placeholder="搜索资源、学科或主题……"></div><div class="resource-note">公开资源会在审核通过后显示；你上传的资料可以在审核期间继续保留。</div><div class="cards resource-grid" id="resources">${resourceList()}</div></section></div>`}
function resourceList(q='',type='all'){let list=state.resources.filter(r=>(type==='all'||r.resource_type===type)&&(!q||(r.title+' '+(r.description||'')+' '+subjectName(r.subject_id)+' '+(r.topic||'')).toLowerCase().includes(q.toLowerCase())));return list.length?list.map(r=>`<article class="card resource"><div class="res-top"><div class="res-icon">${esc((r.resource_type||'FILE').slice(0,1).toUpperCase())}</div><span class="resource-status ${esc(r.status)}">${resourceStatusLabel(r.status)}</span></div><div class="file-type">${esc(resourceTypeLabel(r.resource_type))} · ${esc(subjectName(r.subject_id))}</div><h3>${esc(r.title)}</h3><p>${esc(r.description||'')}</p>${r.topic?`<small class="resource-topic">${esc(r.topic)}</small>`:''}<button class="resource-open" onclick="openResource('${r.id}')">查看资料 →</button></article>`).join(''):`<div class="empty" style="grid-column:1/-1">没有找到相关资源。</div>`}
function openResource(id){const r=state.resources.find(x=>x.id===id);if(!r)return;if(r.status!=='approved'&&!(state.user&&([r.uploader_id,state.user.id].includes(state.user.id)||canManageResources()))){toast('该资料还在审核中');return}const url=r.external_url||(r.file_path&&configured?supabase.storage.from('episteme-resources').getPublicUrl(r.file_path).data.publicUrl:'');if(url)window.open(url,'_blank');else toast('资源文件尚未绑定')}
function uploadResource(){if(!state.user)return auth();modal('上传资料',`<form class="form" id="resForm"><label>标题<input name="title" required placeholder="例如：IGCSE Physics Forces 笔记"></label><label>学科<select name="subject">${state.subjects.map(s=>`<option value="${s.id}">${esc(s.name)} ${s.code?`· ${esc(s.code)}`:''}</option>`).join('')}</select></label><label>类型<select name="type"><option value="note">笔记</option><option value="paper">真题</option><option value="handout">讲义</option><option value="tool">工具</option><option value="other">其他</option></select></label><label>Topic<input name="topic" placeholder="例如：Forces / Trigonometry / Poetry"></label><label>文件<input type="file" name="file" required></label><label>说明<textarea name="description" placeholder="简单介绍这份资料适合什么情况使用……"></textarea></label><p class="help">上传后会进入待审核状态。学科负责人审核通过后，其他成员就能在资源库中看到。</p><button class="submit">上传并提交审核</button></form>`);document.getElementById('resForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),file=f.get('file');if(!file||!file.size)return toast('请选择文件');const path=`${state.user.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await supabase.storage.from('episteme-resources').upload(path,file);if(up.error)return toast(up.error.message);const ins=await supabase.from('resources').insert({title:f.get('title'),description:f.get('description'),subject_id:f.get('subject'),topic:f.get('topic'),resource_type:f.get('type'),file_path:path,uploader_id:state.user.id,status:'pending'});if(ins.error){await supabase.storage.from('episteme-resources').remove([path]);return toast(ins.error.message)}closeModal();toast('资料已上传，等待学科负责人审核');await loadAll();render()}}
function adminResources(){if(!canManageResources())return `<section class="page-hero"><div class="container page-hero-inner"><div class="eyebrow">RESOURCE MANAGEMENT</div><h1>资料后台</h1><p>这个页面仅对学科负责人和管理员开放。</p></div></section><section class="container content"><div class="panel"><h2>需要负责人权限</h2><p class="help">请登录一个 role 为 subject_manager 或 admin 的账号。</p></div></section>`;return `<div class="admin-page"><section class="page-hero admin-hero"><div class="container page-hero-inner"><div class="eyebrow">SUBJECT MANAGER · RESOURCE DESK</div><h1>资源审核后台</h1><p>集中查看社区上传的资料，按学科和审核状态筛选，并决定哪些资料进入公开资源库。</p></div></section><section class="container content"><div class="admin-toolbar"><div class="filters"><button class="filter active" data-admin-status="all">全部</button><button class="filter" data-admin-status="pending">待审核</button><button class="filter" data-admin-status="approved">已通过</button><button class="filter" data-admin-status="rejected">已拒绝</button></div><select id="adminSubject"><option value="all">全部学科</option>${state.subjects.map(s=>`<option value="${s.id}">${esc(s.name)} ${s.code?`· ${esc(s.code)}`:''}</option>`).join('')}</select></div><div id="adminResources">${adminResourceList()}</div></section></div>`}
function adminResourceList(status='all',subject='all'){let list=state.resources.filter(r=>(status==='all'||r.status===status)&&(subject==='all'||String(r.subject_id)===String(subject)));return list.length?`<div class="admin-resource-list">${list.map(r=>`<article class="admin-resource-row"><div class="admin-resource-main"><div class="admin-resource-icon">${esc((r.resource_type||'F').slice(0,1).toUpperCase())}</div><div><div class="eyebrow">${esc(resourceTypeLabel(r.resource_type))} · ${esc(subjectName(r.subject_id))}</div><h3>${esc(r.title)}</h3><p>${esc(r.description||'暂无说明')}</p><small>上传者：${esc(r.profiles?.username||'成员')} · ${fmtDate(r.created_at)} · ${resourceStatusLabel(r.status)}</small></div></div><div class="admin-resource-actions"><button class="secondary" onclick="openResource('${r.id}')">查看</button>${r.status!=='approved'?`<button class="approve" onclick="reviewResource('${r.id}','approved')">通过</button>`:''}${r.status!=='rejected'?`<button class="reject" onclick="reviewResource('${r.id}','rejected')">拒绝</button>`:''}<button class="danger" onclick="deleteResource('${r.id}')">删除</button></div></article>`).join('')}</div>`:`<div class="empty">当前筛选条件下没有资料。</div>`}
async function reviewResource(id,status){if(!canManageResources())return;const {error}=await supabase.from('resources').update({status}).eq('id',id);if(error)toast(error.message);else{toast(status==='approved'?'资料已通过':'资料已拒绝');await loadAll();render()}}
async function deleteResource(id){if(!canManageResources())return;if(!confirm('确定删除这份资料吗？此操作会从资源库记录中移除。'))return;const r=state.resources.find(x=>x.id===id);const {error}=await supabase.from('resources').delete().eq('id',id);if(error)return toast(error.message);if(r?.file_path)await supabase.storage.from('episteme-resources').remove([r.file_path]);toast('资料已删除');await loadAll();render()}
function about(){return `<div class="about-page">
<section class="about-hero"><div class="container about-hero-grid"><div class="about-copy"><div class="eyebrow">ABOUT EPISTEME</div><h1>关于知屿</h1><div class="about-rule"></div><p>True knowledge belongs to no one.</p><p class="about-lead">我们是一个由高中生发起并主导的线上学习共同体。通过同伴授课、资源共享、答疑互助，并结合 AI 工具辅助学习，我们希望让知识不再被一次性的聊天记录带走。</p><a class="about-scroll" href="#about-mission">了解我们的故事 ↓</a></div><div class="about-visual"><div class="visual-window"></div><div class="visual-sun"></div><div class="visual-book b1"></div><div class="visual-book b2"></div><div class="visual-leaf l1"></div><div class="visual-leaf l2"></div><div class="visual-cup"></div><div class="visual-label">EPISTEME · 知识共同体</div></div></div></section>
<section class="about-section about-mission" id="about-mission"><div class="container about-split"><div class="about-number">01</div><div class="about-section-copy"><div class="eyebrow">OUR MISSION</div><h2>让学习资源<br><em>被更多人拥有。</em></h2><p>让更多学生能够获得可靠、可及的学习资源，并通过同伴互助共同成长。我们希望把“我会，所以我教你”变成一个可以持续循环的社区机制。</p><a href="#about-vision" class="text-link">继续了解 →</a></div><div class="about-image-card mission-card"><span>Education<br>for everyone,<br>by everyone.</span></div></div></section>
<section class="about-section about-vision" id="about-vision"><div class="container about-split reverse"><div class="about-number gold">02</div><div class="about-section-copy"><div class="eyebrow">OUR VISION</div><h2>让知识可以<br><em>跨年级留下来。</em></h2><p>建立一个可以不断积累知识、跨年级传承，并由学生自己持续维护的学习共同体。上一届留下的答案，会成为下一届的起点。</p><a href="#about-values" class="text-link gold-link">看看我们的价值观 →</a></div><div class="vision-grid"><div><b>开放包容</b><p>欢迎每一位愿意学习和分享的人。</p></div><div><b>共同成长</b><p>在互助中学习，在交流中进步。</p></div><div><b>知识传承</b><p>让有价值的内容被记录、整理并延续。</p></div><div><b>长期影响</b><p>把一次帮助变成长期可使用的资源。</p></div></div></div></section>
<section class="about-values" id="about-values"><div class="container"><div class="about-number lavender-number">03</div><div class="eyebrow">CORE VALUES</div><h2>Share · Collaborate · Understand · Preserve</h2><div class="values-rich"><div class="value-rich sage-v"><span>01</span><b>Share</b><p>知识不应该因为拥有者不同而产生壁垒。</p></div><div class="value-rich blue-v"><span>02</span><b>Collaborate</b><p>学习不应该只有竞争，也可以通过合作共同进步。</p></div><div class="value-rich lavender-v"><span>03</span><b>Understand</b><p>我们不仅关注答案，更关注问题背后的逻辑。</p></div><div class="value-rich cream-v"><span>04</span><b>Preserve</b><p>有价值的讨论不应该随着聊天记录被刷掉。</p></div></div></div></section>
<section class="about-join"><div class="container join-inner"><div><div class="about-number gold">04</div><div class="eyebrow">JOIN US</div><h2>把下一份知识<br>留给下一位学习者。</h2><p>如果你愿意分享一道题、一份笔记、一节课，或者只是一次认真回答，你已经在参与知屿。</p><button class="primary" onclick="location.hash='#/community'">加入知屿 →</button></div><div class="join-stats"><div><strong>01</strong><span>学习共同体</span></div><div><strong>∞</strong><span>知识持续积累</span></div><div><strong>→</strong><span>一代传给一代</span></div></div></div></section>
</div>`}
function setupNotice(k,t){return hero(k,t,"当前前端已经完成。只需在 config.js 填入 Supabase URL + Publishable Key，再运行 SQL，即可开启真正的动态功能。")+`<section class="container content"><div class="panel setup"><h2>还差最后一步配置</h2><ol><li>创建 Supabase 项目</li><li>在 SQL Editor 运行项目里的 <code>supabase/schema.sql</code></li><li>打开 <code>config.js</code>，填写 Project URL 和 Publishable Key</li><li>把整个文件夹上传 GitHub Pages</li></ol><p>不需要服务器，不需要 Node.js。GitHub Pages 继续负责网站，Supabase 负责数据库、登录、实时消息和资源存储。</p></div></section>`}
function auth(){modal(state.user?"我的账号":"登录 / 注册",state.user?`<div class="account"><div class="avatar">${esc((state.profile?.username||"U")[0].toUpperCase())}</div><h3>${esc(state.profile?.username||"Member")}</h3><p>${esc(state.user.email||"")}</p><p class="help">角色：${esc(state.profile?.role||"student")}</p><button class="submit" id="logout">退出登录</button></div>`:`<div class="auth-tabs"><button class="filter active" id="loginTab">登录</button><button class="filter" id="signupTab">注册</button></div><form class="form" id="authForm"><label>昵称<input name="username" placeholder="注册时填写"></label><label>邮箱<input type="email" name="email" required></label><label>密码<input type="password" name="password" minlength="6" required></label><p class="help">第一版使用 Supabase Auth。密码不会存进 Episteme 自己的数据库。</p><button class="submit">继续</button></form>`);if(state.user){document.getElementById("logout").onclick=async()=>{await supabase.auth.signOut();closeModal();toast("已退出");location.hash="#/"};return}let mode="login";document.getElementById("loginTab").onclick=()=>{mode="login";document.getElementById("signupTab").classList.remove("active");document.getElementById("loginTab").classList.add("active")};document.getElementById("signupTab").onclick=()=>{mode="signup";document.getElementById("loginTab").classList.remove("active");document.getElementById("signupTab").classList.add("active")};document.getElementById("authForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);let res;if(mode==="signup")res=await supabase.auth.signUp({email:f.get("email"),password:f.get("password"),options:{data:{username:f.get("username")||f.get("email").split("@")[0]}}});else res=await supabase.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(res.error)toast(res.error.message);else{closeModal();toast(mode==="signup"?"注册成功，请检查邮箱（如开启邮箱确认）":"登录成功")}}}
async function render(){navActive();const r=route();document.body.dataset.route=(r||"/").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"");const main=document.getElementById("main");if(r==="/")main.innerHTML=home();else if(r==="/community")main.innerHTML=community();else if(r.startsWith("/question/"))main.innerHTML=questionDetail(r.split("/")[2]);else if(r==="/courses")main.innerHTML=courses();else if(r.startsWith("/course/"))main.innerHTML=courseDetail(r.split("/")[2]);else if(r==="/library")main.innerHTML=library();else if(r==="/admin/resources")main.innerHTML=adminResources();else if(r==="/about")main.innerHTML=about();else main.innerHTML=home();bind();if(r==="/community")await loadChat();if(r.startsWith("/question/"))bindAnswer(r.split("/")[2])}
function bind(){
 document.querySelectorAll('.channel').forEach(b=>b.onclick=()=>{document.querySelectorAll('.channel').forEach(x=>x.classList.remove('active'));b.classList.add('active');const st=document.querySelector('.filter.active')?.dataset.status||'全部';document.getElementById('questions').innerHTML=questionList(b.dataset.sub,st,state.query)});
 document.querySelectorAll('.filter[data-status]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter[data-status]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const sub=document.querySelector('.channel.active')?.dataset.sub||'全部';document.getElementById('questions').innerHTML=questionList(sub,b.dataset.status,state.query)});
 const cf=document.getElementById('chatForm');if(cf)cf.onsubmit=async e=>{e.preventDefault();const content=new FormData(cf).get('content');if(!content?.trim())return;const {error}=await supabase.from('messages').insert({channel:'general',author_id:state.user.id,content:content.trim()});if(error)toast(error.message);else cf.reset()};
 const rs=document.getElementById('resSearch');let resourceType='all';if(rs)rs.oninput=e=>document.getElementById('resources').innerHTML=resourceList(e.target.value,resourceType);
 document.querySelectorAll('[data-resource-type]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-resource-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');resourceType=b.dataset.resourceType;document.getElementById('resources').innerHTML=resourceList(rs?.value||'',resourceType)});
 const ars=document.getElementById('adminSubject');let adminStatus='all';if(ars)ars.onchange=e=>document.getElementById('adminResources').innerHTML=adminResourceList(adminStatus,e.target.value);
 document.querySelectorAll('[data-admin-status]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-admin-status]').forEach(x=>x.classList.remove('active'));b.classList.add('active');adminStatus=b.dataset.adminStatus;document.getElementById('adminResources').innerHTML=adminResourceList(adminStatus,ars?.value||'all')});
 const search=document.getElementById('globalSearch');if(search)search.oninput=globalSearch;
}
function bindAnswer(id){const f=document.getElementById("answerForm");if(f)f.onsubmit=async e=>{e.preventDefault();const content=new FormData(f).get("content");const {error}=await supabase.from("answers").insert({question_id:id,author_id:state.user.id,content});if(error)toast(error.message);else{await supabase.from("questions").update({status:"discussing"}).eq("id",id);f.reset();toast("回答已提交")}}}
function globalSearch(e){const q=e.target.value.trim().toLowerCase();const box=document.getElementById("searchResults");if(!q){box.innerHTML="";return}const arr=[...state.questions.map(x=>({t:x.title,k:"Question Card",h:"#/question/"+x.id})),...state.courses.map(x=>({t:x.title,k:"Course",h:"#/course/"+x.id})),...state.resources.map(x=>({t:x.title,k:"Resource",h:"#/library"}))].filter(x=>x.t.toLowerCase().includes(q)).slice(0,10);box.innerHTML=arr.length?arr.map(x=>`<a href="${x.h}"><b>${esc(x.t)}</b><small>${x.k}</small></a>`).join(""):`<div class="empty">没有找到结果。</div>`}
document.getElementById("authBtn").onclick=auth;
document.getElementById("searchBtn").onclick=()=>document.getElementById("searchPanel").classList.add("open");
document.getElementById("closeSearch").onclick=()=>document.getElementById("searchPanel").classList.remove("open");
document.getElementById("menuBtn").onclick=()=>document.getElementById("mobileNav").classList.toggle("open");
document.querySelectorAll("#mobileNav a").forEach(a=>a.onclick=()=>document.getElementById("mobileNav").classList.remove("open"));
window.addEventListener("hashchange",render);
window.auth=auth;window.ask=ask;window.playLesson=playLesson;window.uploadResource=uploadResource;window.openResource=openResource;window.reviewResource=reviewResource;window.deleteResource=deleteResource;
boot();
