import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};
const sb=C.SUPABASE_URL&&C.SUPABASE_PUBLISHABLE_KEY?createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY):null;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const state={subjects:[],courses:[],lessons:[],subject:null,query:"",loaded:false};
const route=()=>location.hash.slice(1)||"/";
const subjectName=id=>state.subjects.find(s=>s.id===id)?.name||"未分类";
function isCoursesRoute(){return /^\/courses(?:\/|$)/.test(route())||/^\/course(?:\/|$)/.test(route())}
function palette(i){return ["sage","blue","lav","cream"][i%4]}
function sectionLabel(c){const t=String(c.course_type||"").toLowerCase();if(t.includes("ig")||t.includes("exam"))return "IGCSE QUESTION WALKTHROUGH";if(t.includes("advanced")||t.includes("extension"))return "EXTENSION & TOPICS";return "TEXTBOOK CONTENT"}
function duration(sec){return sec?`${Math.max(1,Math.round(sec/60))} min`:"录课"}
async function load(){if(!sb){state.loaded=true;return}const [s,c,l]=await Promise.all([sb.from("subjects").select("id,name,code").order("name"),sb.from("courses").select("*,subjects(name,code)").eq("status","published").eq("is_hidden",false).order("created_at",{ascending:false}),sb.from("course_lessons").select("*").order("lesson_order")]);state.subjects=s.data||[];state.courses=c.data||[];state.lessons=l.data||[];state.loaded=true}
function subjectSidebar(){return `<aside class="courses-v2-side"><div class="courses-v2-side-title">SUBJECTS</div><button class="courses-v2-subject ${state.subject===null?"active":""}" data-s="all"><span class="courses-v2-dot"></span><span>全部学科</span></button>${state.subjects.map(s=>`<button class="courses-v2-subject ${state.subject===s.id?"active":""}" data-s="${s.id}"><span class="courses-v2-dot"></span><span>${esc(s.name)}${s.code?` · ${esc(s.code)}`:""}</span></button>`).join("")}</aside>`}
function card(c,i){const ls=state.lessons.filter(x=>x.course_id===c.id);const thumb=c.thumbnail_url?`<img src="${esc(c.thumbnail_url)}" alt="" loading="lazy">`:`<span>${esc(subjectName(c.subject_id))}</span>`;return `<article class="course-v2-card" data-id="${c.id}"><div class="course-v2-thumb ${palette(i)}">${thumb}<span class="course-v2-play">▶</span></div><div class="course-v2-body"><div class="course-v2-eyebrow">${esc(sectionLabel(c))}</div><div class="course-v2-title">${esc(c.title)}</div><p class="course-v2-desc">${esc(c.description||"同伴授课，帮助理解概念、原理与知识之间的联系。")}</p><div class="course-v2-meta"><span>${esc(subjectName(c.subject_id))}</span><span>${ls.length} 节</span></div></div></article>`}
function list(){let arr=state.courses.filter(c=>state.subject===null||c.subject_id===state.subject);if(state.query){const q=state.query.toLowerCase();arr=arr.filter(c=>(`${c.title} ${c.description||""} ${subjectName(c.subject_id)}`).toLowerCase().includes(q))}return arr.length?arr.map((c,i)=>card(c,i)).join(""):`<div class="courses-v2-empty">${state.loaded?"没有找到相关录课。":"正在加载录课……"}</div>`}
function listing(){return `<div class="courses-v2"><section class="courses-v2-hero"><div class="eyebrow">COURSES · LEARN & SHARE</div><h1>录课</h1><p>把同伴讲解、概念梳理和题目思路长期保存下来。选择一个学科，开始观看。</p></section><div class="courses-v2-shell">${subjectSidebar()}<main class="courses-v2-main"><div class="courses-v2-toolbar"><input class="courses-v2-search" id="coursesV2Search" value="${esc(state.query)}" placeholder="搜索整个录课库……"><span class="courses-v2-count">${listCount()} 节课程</span></div><div class="courses-v2-grid" id="coursesV2Grid">${list()}</div></main></div></div>`}
function listCount(){let arr=state.courses.filter(c=>state.subject===null||c.subject_id===state.subject);if(state.query){const q=state.query.toLowerCase();arr=arr.filter(c=>(`${c.title} ${c.description||""} ${subjectName(c.subject_id)}`).toLowerCase().includes(q))}return arr.length}
function videoHtml(l){if(!l)return `<div class="video-placeholder">这一课程还没有可播放的视频。</div>`;const p=l.video_provider||"supabase",ref=l.video_ref||"",url=l.video_url||"";if(p==="bilibili"){const b=(ref.match(/BV[0-9A-Za-z]+/)||[])[0]||ref;return b?`<iframe src="https://player.bilibili.com/player.html?bvid=${encodeURIComponent(b)}&autoplay=0&danmaku=1" allowfullscreen referrerpolicy="no-referrer-when-downgrade"></iframe>`:`<div class="video-placeholder">Bilibili 视频地址尚未配置。</div>`}if(url)return `<video controls playsinline src="${esc(url)}"></video>`;return `<div class="video-placeholder">这一章节还没有可播放的视频。</div>`}
function detail(id){const c=state.courses.find(x=>x.id===id);if(!c)return `<div class="course-detail-v2"><div class="empty">课程不存在。</div></div>`;const ls=state.lessons.filter(x=>x.course_id===id).sort((a,b)=>(a.lesson_order||0)-(b.lesson_order||0));const active=ls[0];return `<div class="course-detail-v2"><section class="course-detail-v2-head"><a class="back" href="#/courses">← 返回录课</a><div class="eyebrow">${esc(sectionLabel(c))}</div><h1>${esc(c.title)}</h1><p>${esc(subjectName(c.subject_id))}${c.profiles?.username?` · ${esc(c.profiles.username)}`:""}</p></section><section class="course-detail-v2-player"><div><div class="course-detail-v2-video" id="courseV2Video">${videoHtml(active)}</div><div class="course-detail-v2-info"><h2>课程简介</h2><p>${esc(c.description||"暂无简介")}</p></div><div class="course-detail-v2-discussion"><h2>课程讨论</h2><p>在这里提出问题、分享思路，让一节录课变成可以继续讨论的知识。</p><a href="#/community">进入讨论群 →</a></div></div><aside class="course-detail-v2-lessons"><div class="course-detail-v2-lessons-title">LESSONS</div>${ls.length?ls.map((l,i)=>`<button class="course-detail-v2-lesson ${i===0?"active":""}" data-l="${l.id}"><span>${String(i+1).padStart(2,"0")} · ${esc(l.title)}</span><small>${duration(l.duration_seconds)}</small></button>`).join(""):`<div class="empty">还没有章节。</div>`}</aside></section></div>`}
function render(){if(!isCoursesRoute())return;const main=document.getElementById("main");if(!main)return;main.classList.add("courses-v2-host");main.innerHTML=route().startsWith("/course/")?detail(route().split("/")[2]):listing();bind()}
function bind(){document.querySelectorAll(".courses-v2-subject").forEach(b=>b.onclick=()=>{state.subject=b.dataset.s==="all"?null:Number(b.dataset.s);render()});const q=document.getElementById("coursesV2Search");if(q){q.oninput=()=>{state.query=q.value;const grid=document.getElementById("coursesV2Grid");if(grid)grid.innerHTML=list();const c=document.querySelector(".courses-v2-count");if(c)c.textContent=`${listCount()} 节课程`;bindCards()};q.onkeydown=e=>{if(e.key==="Enter")e.preventDefault()}}bindCards();document.querySelectorAll(".course-detail-v2-lesson").forEach(b=>b.onclick=()=>{const l=state.lessons.find(x=>x.id===b.dataset.l);if(!l)return;document.querySelectorAll(".course-detail-v2-lesson").forEach(x=>x.classList.remove("active"));b.classList.add("active");const v=document.getElementById("courseV2Video");if(v)v.innerHTML=videoHtml(l)})}
function bindCards(){document.querySelectorAll(".course-v2-card").forEach(c=>c.onclick=()=>location.hash=`#/course/${c.dataset.id}`)}
async function boot(){if(!isCoursesRoute())return;await load();render()}
boot();window.addEventListener("hashchange",()=>{if(isCoursesRoute()){render()}else{document.getElementById("main")?.classList.remove("courses-v2-host")}});
