import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};
const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);
let sessionId=null,studyStarted=0,studyTimer=null,observer=null;
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const fmtHours=s=>{const h=(Number(s||0)/3600);return h<0.1?'0.0':h.toFixed(1)};
const css=`.dash-page{padding-bottom:70px}.dash-hero{padding:54px 0 30px}.dash-hero h1{margin:6px 0 10px;font:500 clamp(34px,5vw,58px) Georgia,"Songti SC",serif;color:#405248}.dash-hero p{color:#69766e;line-height:1.8}.dash-eyebrow{font-size:11px;letter-spacing:.16em;color:#819086}.dash-grid{display:grid;grid-template-columns:1.4fr .8fr;gap:16px}.dash-panel{border:1px solid #e0e5df;border-radius:18px;background:#fff;padding:20px}.dash-panel h2{font:500 24px Georgia,"Songti SC",serif;color:#46574e;margin:0 0 5px}.dash-sub{font-size:12px;color:#89938d;margin-bottom:15px}.dash-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:16px}.dash-stat{padding:16px;border-radius:14px;background:#f4f7f2}.dash-stat strong{display:block;font:500 27px Georgia,serif;color:#4d6255}.dash-stat span{font-size:11px;color:#7d8981}.dash-favs{display:grid;gap:9px}.dash-fav{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 13px;border:1px solid #e6eae5;border-radius:12px;text-decoration:none;color:#4e5d55}.dash-fav:hover{background:#f8faf7}.dash-fav b{display:block;font-size:13px}.dash-fav small{display:block;margin-top:4px;color:#8a948d;font-size:10px}.dash-empty{padding:22px;border:1px dashed #d9dfd8;border-radius:12px;color:#89938d;font-size:12px}.dash-profile{background:#eef4eb}.dash-avatar{width:54px;height:54px;border-radius:50%;display:grid;place-items:center;background:#fff;font:500 25px Georgia,serif;color:#4b6153;margin-bottom:14px}.dash-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.dash-actions a{padding:9px 12px;border-radius:9px;border:1px solid #d5ddd4;color:#506158;text-decoration:none;font-size:12px}.dash-section{margin-top:16px}.dash-fav-btn{border:1px solid #d7ded5;background:#fff;color:#637067;border-radius:999px;padding:6px 9px;cursor:pointer;font-size:11px}.dash-fav-btn.on{background:#eef4eb;color:#47604f}.dash-inline{display:flex;align-items:center;justify-content:space-between;gap:10px}.dash-about{margin-top:18px;padding:55px 0 65px;background:#f3f0e8}.dash-about-grid{display:grid;grid-template-columns:.75fr 1.25fr;gap:35px;align-items:start}.dash-about h2{font:500 clamp(30px,4vw,46px) Georgia,"Songti SC",serif;color:#4b554f;margin:7px 0 15px}.dash-about p{color:#68736d;line-height:1.9;font-size:13px}.dash-about .about-values{display:grid;grid-template-columns:1fr 1fr;gap:10px}.dash-about .about-value{padding:16px;border:1px solid #dddcd2;border-radius:14px;background:rgba(255,255,255,.55)}.dash-about .about-value b{font-size:13px;color:#536258}.dash-about .about-value p{font-size:11px;margin:6px 0 0;line-height:1.6}@media(max-width:800px){.dash-grid,.dash-about-grid{grid-template-columns:1fr}.dash-stats{grid-template-columns:1fr 1fr}.dash-about .about-values{grid-template-columns:1fr}}
`;
function style(){if(document.getElementById('dashboardStyle'))return;const s=document.createElement('style');s.id='dashboardStyle';s.textContent=css;document.head.appendChild(s)}
async function current(){const {data:{session}}=await sb.auth.getSession();return session}
async function startStudy(){if(studyTimer)return;const s=await current();if(!s)return;studyStarted=Date.now();const {data,error}=await sb.from('study_sessions').insert({user_id:s.user.id,started_at:new Date().toISOString(),duration_seconds:0}).select('id').single();if(error)return;sessionId=data.id;const tick=async()=>{if(!sessionId)return;const active=Math.floor((Date.now()-studyStarted)/1000);await sb.from('study_sessions').update({duration_seconds:active}).eq('id',sessionId);};studyTimer=setInterval(tick,60000);document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'){studyStarted=Date.now();}else if(sessionId){await tick();}})}
async function loadData(){const s=await current();if(!s)return null;const [p,f,ss]=await Promise.all([sb.from('profiles').select('username,created_at,role').eq('id',s.user.id).maybeSingle(),sb.from('user_favorites').select('*').eq('user_id',s.user.id).order('created_at',{ascending:false}),sb.from('study_sessions').select('duration_seconds').eq('user_id',s.user.id)]);return {session:s,profile:p.data,favorites:f.data||[],study:(ss.data||[]).reduce((n,x)=>n+Number(x.duration_seconds||0),0)}}
function favRow(x){const href=x.item_type==='course'?`#/course/${x.item_id}`:'#/library';return `<a class="dash-fav" href="${href}"><span><b>${esc(x.title)}</b><small>${x.item_type==='course'?'视频课':'学习资料'}${x.subject_id?' · 学科':''}</small></span><span>→</span></a>`}
async function dashboard(){style();const d=await loadData();if(!d)return '';const u=d.profile?.username||d.session.user.email?.split('@')[0]||'同学';const total=d.study+(sessionId?Math.floor((Date.now()-studyStarted)/1000):0);return `<div class="dash-page"><section class="container dash-hero"><div class="dash-eyebrow">MY EPISTEME · PERSONAL SPACE</div><h1>亲爱的 ${esc(u)}，<br>你已经在知屿岛上学习了 ${fmtHours(total)} 小时啦 📖</h1><p>这里是属于你的学习空间。你收藏的课程、资料，以及你在知屿留下的学习时间，都会在这里慢慢积累下来。</p></section><section class="container dash-grid"><div><div class="dash-stats"><div class="dash-stat"><strong>${d.favorites.filter(x=>x.item_type==='course').length}</strong><span>收藏视频课</span></div><div class="dash-stat"><strong>${d.favorites.filter(x=>x.item_type==='resource').length}</strong><span>收藏资料</span></div><div class="dash-stat"><strong>${fmtHours(total)}h</strong><span>学习时间</span></div></div><div class="dash-panel"><div class="dash-inline"><div><div class="dash-eyebrow">SAVED</div><h2>我的收藏</h2></div><a href="#/courses" class="dash-actions" style="margin:0"><span>继续学习 →</span></a></div><div class="dash-favs" style="margin-top:14px">${d.favorites.length?d.favorites.map(favRow).join(''):`<div class="dash-empty">还没有收藏。去视频课或资源库，看到喜欢的内容就点一下收藏。</div>`}</div></div></div><aside><div class="dash-panel dash-profile"><div class="dash-avatar">${esc(u[0]?.toUpperCase()||'U')}</div><div class="dash-eyebrow">YOUR ACCOUNT</div><h2>${esc(u)}</h2><p class="dash-sub">${esc(d.profile?.role||'student')} · 知屿学习者</p><div class="dash-actions"><a href="#/courses">去学习</a><a href="#/library">找资料</a><a href="#/community">去讨论</a></div></div><div class="dash-panel dash-section"><div class="dash-eyebrow">KEEP GOING</div><h2>让知识留下来。</h2><p class="dash-sub">每一次观看、收藏、提问和回答，都会成为你的学习轨迹。</p></div></aside></section></div>`}
async function favorite(type,id,title,subjectId,btn){const s=await current();if(!s){window.auth?.();return}const {data:old}=await sb.from('user_favorites').select('id').eq('user_id',s.user.id).eq('item_type',type).eq('item_id',id).maybeSingle();if(old){await sb.from('user_favorites').delete().eq('id',old.id);btn?.classList.remove('on');if(btn)btn.textContent='♡ 收藏'}else{const {error}=await sb.from('user_favorites').insert({user_id:s.user.id,item_type:type,item_id:id,title,subject_id:subjectId});if(!error){btn?.classList.add('on');if(btn)btn.textContent='♥ 已收藏'}}}
async function decorateFavorites(){const s=await current();if(!s)return;const {data}=await sb.from('user_favorites').select('item_type,item_id').eq('user_id',s.user.id);const set=new Set((data||[]).map(x=>x.item_type+':'+x.item_id));document.querySelectorAll('.course-card').forEach(el=>{const m=(el.getAttribute('onclick')||'').match(/course\/(.+?)['\"]/);if(!m||el.querySelector('.dash-fav-btn'))return;const id=m[1];const c=window.__epState?.courses?.find?.(x=>x.id===id);const b=document.createElement('button');b.className='dash-fav-btn'+(set.has('course:'+id)?' on':'');b.textContent=set.has('course:'+id)?'♥ 已收藏':'♡ 收藏';b.onclick=e=>{e.stopPropagation();favorite('course',id,c?.title||el.querySelector('h3')?.textContent||'视频课',c?.subject_id,b)};el.querySelector('.card-body')?.appendChild(b)});}
function injectNav(){document.querySelectorAll('#nav a[href="#/"]').forEach(a=>a.textContent='我的知屿');document.querySelectorAll('#mobileNav a[href="#/"]').forEach(a=>a.textContent='我的知屿');document.querySelectorAll('#nav a[href="#/about"],#mobileNav a[href="#/about"]').forEach(a=>a.style.display='none');document.querySelectorAll('.footer-links a[href="#/about"]').forEach(a=>a.style.display='none')}
async function route(){const s=await current();injectNav();if(s&&(!location.hash||location.hash==='#'||location.hash==='#/')){history.replaceState(null,'',location.pathname+location.search+'#/dashboard');}if(!s&&location.hash==='#/dashboard'){location.hash='#/';return}if(location.hash==='#/dashboard'){const main=document.getElementById('main');if(main)main.innerHTML=await dashboard();}}
async function init(){style();await route();await startStudy();observer=new MutationObserver(()=>{injectNav();decorateFavorites();});observer.observe(document.body,{childList:true,subtree:true});sb.auth.onAuthStateChange(async(_e,s)=>{if(s){if(!location.hash||location.hash==='#/'||location.hash==='#'){location.hash='#/dashboard';}await startStudy();}else if(location.hash==='#/dashboard')location.hash='#/';});window.addEventListener('hashchange',route);setInterval(async()=>{if(location.hash==='#/dashboard'){const el=document.querySelector('.dash-hero h1');if(el){const d=await loadData();if(d)el.innerHTML=`亲爱的 ${esc(d.profile?.username||'同学')}，<br>你已经在知屿岛上学习了 ${fmtHours(d.study+(sessionId?Math.floor((Date.now()-studyStarted)/1000):0))} 小时啦 📖`;}}},60000)}setTimeout(init,0);
