(()=>{
const LANGS={'zh-CN':'简体中文',en:'English',ja:'日本語',ko:'한국어',de:'Deutsch',fr:'Français',es:'Español',ru:'Русский'};
const EN={'首页':'Home','讨论群':'Community','视频课':'Courses','录课':'Courses','资源库':'Library','关于我们':'About Us','后台':'Admin','登录 / 注册':'Log in / Sign up','我的账号':'My Account','返回网站':'Back to site','退出登录':'Sign out','账号管理':'Account management','语言偏好':'Language preference','简体中文':'Simplified Chinese','English':'English','日本語':'Japanese','한국어':'Korean','Deutsch':'German','Français':'French','Español':'Spanish','Русский':'Russian','通知':'Notifications','全部已读':'Mark all as read','暂无新通知':'No new notifications','保存':'Save','取消':'Cancel','确认':'Confirm','打开':'Open','查看':'View','预览':'Preview','下载':'Download','进入':'Enter'};
const original=new WeakMap();let applying=false,current='zh-CN';
const tr=s=>{if(current==='zh-CN')return s;let out=EN[s]||s;if(out===s)for(const [zh,en] of Object.entries(EN))if(s.includes(zh))out=out.split(zh).join(en);return out};
function translateNode(root){if(!root||applying)return;applying=true;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const p=node.parentElement;if(!p||['SCRIPT','STYLE'].includes(p.tagName)||p.closest('[data-i18n-ignore]'))continue;const raw=original.get(node)??node.nodeValue;if(!original.has(node))original.set(node,raw);const trimmed=raw.trim();if(!trimmed)continue;const next=tr(trimmed);if(next!==trimmed)node.nodeValue=raw.replace(trimmed,next)}root.querySelectorAll?.('input[placeholder],textarea[placeholder],input[title],button[title]').forEach(el=>{const attr=el.hasAttribute('placeholder')?'placeholder':'title';const key=attr==='placeholder'?'i18nPlaceholder':'i18nTitle';const raw=el.dataset[key]||el.getAttribute(attr)||'';if(!el.dataset[key])el.dataset[key]=raw;el.setAttribute(attr,tr(raw))});applying=false}
async function profileLanguage(){try{const C=window.EPISTEME_CONFIG||{};if(!C.SUPABASE_URL||!C.SUPABASE_PUBLISHABLE_KEY)return null;const{createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);const{data:{session}}=await sb.auth.getSession();if(!session)return null;const{data}=await sb.from('profiles').select('language').eq('id',session.user.id).maybeSingle();return data?.language||null}catch{return null}}
async function setLanguage(lang,persist=true){if(!LANGS[lang])lang='zh-CN';current=lang;localStorage.setItem('episteme-language',lang);localStorage.setItem('episteme_language',lang);document.documentElement.lang=lang;translateNode(document.body);if(persist&&!document.body.classList.contains('auth-page')){try{const C=window.EPISTEME_CONFIG||{};if(C.SUPABASE_URL&&C.SUPABASE_PUBLISHABLE_KEY){const{createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);const{data:{session}}=await sb.auth.getSession();if(session)await sb.rpc('update_my_profile',{p_language:lang})}}catch(e){console.warn('language profile sync skipped',e)}}}
async function boot(){const isAuth=document.body.classList.contains('auth-page');if(isAuth)await setLanguage('en',false);else{const saved=localStorage.getItem('episteme-language')||localStorage.getItem('episteme_language');await setLanguage(await profileLanguage()||saved||'zh-CN',false)}const observer=new MutationObserver(()=>{if(!applying)translateNode(document.body)});observer.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.EpistemeI18n={setLanguage,translate:translateNode,getLanguage:()=>current,t:tr,langs:LANGS};
})();