import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import * as tus from "https://cdn.jsdelivr.net/npm/tus-js-client@4.3.1/+esm";
const C=window.EPISTEME_CONFIG||{},sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY),BUCKET="episteme-library",ref=(()=>{try{return new URL(C.SUPABASE_URL).hostname.split('.')[0]}catch{return''}})();
const UI={subject:null,parent:null,subjects:[],view:localStorage.getItem('ep-library-view')||'grid'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function loadSubjects(){const {data}=await sb.from('subjects').select('id,name,code').order('name');UI.subjects=data||[]}
function isManager(){return !!document.querySelector('.lib-actions .primary,.lib-actions .secondary')}
function patchNav(){const a=window.__epLibrary;if(!a||a.__finderUI)return false;const s=a.subject,f=a.folder,h=a.home;a.subject=id=>{UI.subject=+id;UI.parent=null;s(id);setTimeout(enhance,40)};a.folder=id=>{UI.parent=id;f(id);setTimeout(enhance,40)};a.home=()=>{UI.subject=null;UI.parent=null;h();setTimeout(enhance,40)};a.__finderUI=true;return true}
function sidebar(){const side=document.createElement('aside');side.className='lib-finder-side';side.innerHTML='<div class="lib-finder-side-title">SUBJECTS</div>'+UI.subjects.map(x=>`<button class="lib-finder-subject ${UI.subject===+x.id?'active':''}" data-sub="${x.id}"><span class="lib-finder-dot"></span><span>${esc(x.name)}</span></button>`).join('');side.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>window.__epLibrary.subject(+b.dataset.sub));return side}
function enhanceShell(){const wrap=document.querySelector('.lib-wrap');if(!wrap||document.querySelector('.lib-finder-shell'))return;if(!wrap.querySelector('.lib-toolbar'))return;const shell=document.createElement('div');shell.className='lib-finder-shell';const main=document.createElement('div');main.className='lib-finder-main';while(wrap.firstChild)main.appendChild(wrap.firstChild);shell.append(sidebar(),main);wrap.appendChild(shell)}
function addToggle(){const bar=document.querySelector('.lib-finder-main .lib-toolbar');if(!bar||bar.querySelector('.lib-finder-toggle'))return;const t=document.createElement('div');t.className='lib-finder-toggle';t.innerHTML=`<button class="${UI.view==='grid'?'active':''}">▦</button><button class="${UI.view==='list'?'active':''}">☷</button>`;t.children[0].onclick=()=>setView('grid');t.children[1].onclick=()=>setView('list');bar.appendChild(t)}
function addDrop(){if(!isManager()||!UI.subject||document.getElementById('libFinderDrop'))return;const main=document.querySelector('.lib-finder-main');const grid=document.getElementById('libGrid')||main?.querySelector('.lib-grid');if(!main||!grid)return;const d=document.createElement('div');d.id='libFinderDrop';d.className='lib-finder-drop';d.innerHTML='<div><strong>拖拽文件到这里</strong>，直接上传到当前栏目。</div><button class="secondary">选择文件</button><input type="file" multiple style="display:none">';const input=d.querySelector('input');d.querySelector('button').onclick=()=>input.click();input.onchange=e=>upload([...e.target.files]);['dragenter','dragover'].forEach(v=>d.addEventListener(v,e=>{e.preventDefault();d.classList.add('drag')}));['dragleave','drop'].forEach(v=>d.addEventListener(v,e=>{e.preventDefault();d.classList.remove('drag')}));d.addEventListener('drop',e=>upload([...e.dataTransfer.files]));main.insertBefore(d,grid)}
function setView(v){UI.view=v;localStorage.setItem('ep-library-view',v);const grid=document.getElementById('libGrid')||document.querySelector('.lib-finder-main .lib-grid');if(grid)grid.classList.toggle('lib-finder-list',v==='list');document.querySelectorAll('.lib-finder-toggle button').forEach((b,i)=>b.classList.toggle('active',(v==='grid'&&i===0)||(v==='list'&&i===1)))}
async function upload(files){if(!files.length||!UI.subject)return;const {data:{session}}=await sb.auth.getSession();if(!session)return;for(const file of files){const {data:item,error}=await sb.from('library_items').insert({subject_id:UI.subject,parent_id:UI.parent||null,name:file.name,item_type:'file',provider:'supabase',mime_type:file.type||null,file_size:file.size,created_by:session.user.id}).select().single();if(error){alert(error.message);continue}const safe=file.name.replace(/[^a-zA-Z0-9._()\- ]/g,'_'),path=`nodes/${item.id}/${safe}`;try{await new Promise(async(resolve,reject)=>{const u=new tus.Upload(file,{endpoint:`https://${ref}.storage.supabase.co/storage/v1/upload/resumable`,retryDelays:[0,3000,5000,10000,20000],headers:{authorization:`Bearer ${session.access_token}`,apikey:C.SUPABASE_PUBLISHABLE_KEY},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:6*1024*1024,metadata:{bucketName:BUCKET,objectName:path,contentType:file.type||'application/octet-stream',cacheControl:'31536000'},onError:reject,onSuccess:resolve});try{const p=await u.findPreviousUploads();if(p.length)u.resumeFromPreviousUpload(p[0]);u.start()}catch(e){reject(e)}});const {error:e}=await sb.from('library_items').update({storage_path:path}).eq('id',item.id);if(e)throw e}catch(e){await sb.from('library_items').delete().eq('id',item.id);alert(`上传失败：${e?.message||e}`)}}location.reload()}
function enhance(){if(location.hash.slice(1)!=='/library')return;patchNav();enhanceShell();addToggle();addDrop();setView(UI.view)}
(async()=>{await loadSubjects();setTimeout(enhance,700);window.addEventListener('hashchange',()=>setTimeout(enhance,80));new MutationObserver(()=>{if(location.hash.slice(1)==='/library'&&!document.querySelector('.lib-finder-shell'))setTimeout(enhance,50)}).observe(document.body,{childList:true,subtree:true})})();
