import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);
let lessons=[];let currentCourse=null;
const esc=s=>String(s??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;","&gt;":"&gt;",'"':"&quot;","'":"&#039;"}[m]||m));
function bvid(l){const s=String(l?.video_ref||l?.video_url||"");const m=s.match(/BV[0-9A-Za-z]+/i);return m?m[0]:null}
function getCourseId(){const m=location.hash.match(/^#\/course\/([^/?]+)/);return m?.[1]||null}
async function load(){const id=getCourseId();if(!id)return;const {data,error}=await sb.from("course_lessons").select("*").eq("course_id",id).order("lesson_order");if(error)return;lessons=data||[];currentCourse=id;bindLessons();renderLesson(lessons[0])}
function renderLesson(l){const host=document.querySelector(".course-player-panel .viewer > div");if(!host||!l)return;const old=host.querySelector("#player, .video-empty, .episteme-bilibili, .episteme-external");if(old)old.remove();if(l.video_provider==="bilibili"){const id=bvid(l);if(!id)return;const iframe=document.createElement("iframe");iframe.className="episteme-bilibili";iframe.allow="autoplay; fullscreen; picture-in-picture";iframe.allowFullscreen=true;iframe.loading="lazy";iframe.referrerPolicy="strict-origin-when-cross-origin";iframe.style.cssText="width:100%;aspect-ratio:16/9;border:0;border-radius:16px;background:#111;display:block";iframe.src=`https://player.bilibili.com/player.html?bvid=${encodeURIComponent(id)}&poster=1&autoplay=0&danmaku=1`;host.prepend(iframe)}else if(l.video_provider==="external"&&l.video_url){const video=document.createElement("video");video.id="player";video.className="video";video.controls=true;video.src=l.video_url;host.prepend(video)}else if(l.storage_path){const {data}=sb.storage.from("episteme-courses").getPublicUrl(l.storage_path);if(data?.publicUrl){const video=document.createElement("video");video.id="player";video.className="video";video.controls=true;video.src=data.publicUrl;host.prepend(video)}}else if(l.video_url){const video=document.createElement("video");video.id="player";video.className="video";video.controls=true;video.src=l.video_url;host.prepend(video)}else{const empty=document.createElement("div");empty.className="video-empty";empty.textContent="课程视频链接尚未添加";host.prepend(empty)}}
function bindLessons(){document.querySelectorAll(".course-player-panel .lesson").forEach((btn,i)=>{const fresh=btn.cloneNode(true);btn.replaceWith(fresh);fresh.addEventListener("click",e=>{e.preventDefault();document.querySelectorAll(".course-player-panel .lesson").forEach(x=>x.classList.remove("active"));fresh.classList.add("active");const id=(fresh.getAttribute("onclick")||"").match(/playLesson\(['\"]([^'\"]+)/)?.[1];const l=lessons.find(x=>x.id===id)||lessons[i];renderLesson(l)})})}
const observer=new MutationObserver(()=>{if(getCourseId()&&document.querySelector(".course-player-panel")){if(currentCourse!==getCourseId())load();else bindLessons()}});observer.observe(document.body,{childList:true,subtree:true});window.addEventListener("hashchange",()=>{currentCourse=null;setTimeout(load,200)});setTimeout(load,500);