import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
let profile,subjects=[],links=[],assignments=[],loading=false,renderTimer=null;
const coord=()=>profile?.role==='coordinator';
const isResourcesTab=()=>{const b=document.querySelector('.admin-tab.active');return !!b&&b.textContent.trim()==='资料审核'};
async function load(){if(loading||!isResourcesTab())return;const host=document.querySelector('#view');if(!host||document.getElementById('memoryPanel'))return;loading=true;try{const {data:{session}}=await sb.auth.getSession();if(!session)return;const p=await sb.from('profiles').select('id,role').eq('id',session.user.id).maybeSingle();profile=p.data;if(!profile||!['coordinator','subject_manager'].includes(profile.role))return;const [s,l,m]=await Promise.all([sb.from('subjects').select('id,name').order('name'),sb.from('knowledge_links').select('*,subjects(name)').order('created_at',{ascending:false}),sb.from('subject_managers').select('user_id,subject_id').eq('user_id',session.user.id)]);subjects=s.data||[];links=l.data||[];assignments=m.data||[];const allowed=new Set(assignments.map(x=>Number(x.subject_id)));if(!coord()){subjects=subjects.filter(s=>allowed.has(Number(s.id)));links=links.filter(l=>l.subject_id!=null&&allowed.has(Number(l.subject_id)));}if(isResourcesTab()&&!document.getElementById('memoryPanel'))render()}finally{loading=false}}
function render(){const host=document.querySelector('#view');if(!host||!isResourcesTab()||document.getElementById('memoryPanel'))return;const managed=subjects;host.insertAdjacentHTML('beforeend',`<div class="admin-card" id="memoryPanel" style="margin-top:20px"><h2>外部记忆 / 引用中心</h2><div class="section-note">超大文件、协作文档或已经存在第三方平台的资料，不必复制进 Episteme。保存原平台链接即可作为长期索引；Episteme 负责学科归档、说明、搜索和隐藏状态。百度网盘目前采用共享链接联动，不把第三方账号密码或密钥放进前端。</div><form id="memoryForm" class="form-grid"><label>标题<input name="title" required placeholder="例如：Chemistry · Topic 4 重点讲义"></label><label>来源<select name="provider"><option value="baidu">百度网盘</option><option value="tencent">腾讯文档</option><option value="google_drive">Google Drive</option><option value="notion">Notion</option><option value="other">其他</option></select></label><label>学科<select name="subject_id" required>${managed.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label>链接<input name="url" type="url" required placeholder="https://... 或第三方共享链接"></label><label>备注<textarea name="description" placeholder="这份外部资料解决什么问题？"></textarea></label><button class="primary">保存到 Episteme 记忆库</button></form><div style="height:22px"></div><div class="manager-list">${links.length?links.map(l=>`<div class="manager-row"><div><b>${esc(l.title)}</b><small>${esc(l.subjects?.name||'未分类')} · ${esc(l.provider)}${l.is_hidden?' · 已隐藏':''}</small></div><div class="admin-actions"><button class="mini" data-memory-open="${esc(l.id)}">打开</button><button class="mini" data-memory-hide="${esc(l.id)}">${l.is_hidden?'显示':'隐藏'}</button><button class="mini danger" data-memory-delete="${esc(l.id)}">删除</button></div></div>`).join(''):'<div class="empty-admin">暂无外部记忆引用</div>'}</div></div>`);bind()}
function bind(){document.getElementById('memoryForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const {data:{session}}=await sb.auth.getSession();const title=String(f.get('title')||'').trim(),url=String(f.get('url')||'').trim();if(!/^https?:\/\//i.test(url))return alert('请输入完整的 http/https 共享链接。');const provider=String(f.get('provider'));if(provider==='baidu'&&!/(pan\.baidu\.com|yun\.baidu\.com)/i.test(url))return alert('来源选择百度网盘时，请填写百度网盘共享链接。');const {error}=await sb.from('knowledge_links').insert({title,provider,subject_id:Number(f.get('subject_id')),url,description:String(f.get('description')||'').trim()||null,created_by:session.user.id});if(error)return alert(error.message);await reload()});document.querySelectorAll('[data-memory-open]').forEach(b=>b.onclick=()=>{const l=links.find(x=>x.id===b.dataset.memoryOpen);if(l)window.open(l.url,'_blank','noopener,noreferrer')});document.querySelectorAll('[data-memory-hide]').forEach(b=>b.onclick=async()=>{const l=links.find(x=>x.id===b.dataset.memoryHide);if(!l)return;const {error}=await sb.from('knowledge_links').update({is_hidden:!l.is_hidden}).eq('id',l.id);if(error)return alert(error.message);await reload()});document.querySelectorAll('[data-memory-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('确定删除这条外部引用？'))return;const {error}=await sb.from('knowledge_links').delete().eq('id',b.dataset.memoryDelete);if(error)return alert(error.message);await reload()})}
async function reload(){document.getElementById('memoryPanel')?.remove();links=[];scheduleLoad(0)}
function scheduleLoad(delay=120){clearTimeout(renderTimer);renderTimer=setTimeout(load,delay)}
const app=document.querySelector('#app');if(app)new MutationObserver(()=>scheduleLoad()).observe(app,{childList:true,subtree:true});
document.addEventListener('click',e=>{if(e.target.closest('.admin-tab'))scheduleLoad(0)});
setTimeout(()=>scheduleLoad(0),300);