import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
let open=false,items=[];
function style(){if(document.getElementById('epNoticeStyle'))return;const s=document.createElement('style');s.id='epNoticeStyle';s.textContent=`.ep-notice-wrap{position:relative;display:inline-flex}.ep-notice-btn{position:relative;width:38px;height:38px;border:1px solid #d8ddd5;border-radius:10px;background:#fff;color:#435247;cursor:pointer;font-size:14px}.ep-notice-badge{position:absolute;right:-3px;top:-4px;min-width:17px;height:17px;padding:0 4px;border-radius:999px;background:#9b5555;color:#fff;font-size:10px;display:grid;place-items:center;font-weight:700}.ep-notice-panel{position:absolute;right:0;top:46px;width:min(390px,88vw);max-height:520px;overflow:auto;background:#fff;border:1px solid #dfe4dd;border-radius:16px;box-shadow:0 18px 50px rgba(30,40,32,.18);z-index:10001}.ep-notice-head{padding:13px 15px;border-bottom:1px solid #edf0eb;display:flex;justify-content:space-between;align-items:center}.ep-notice-item{padding:13px 15px;border-bottom:1px solid #edf0eb;cursor:pointer}.ep-notice-item:hover{background:#f7f9f6}.ep-notice-item.unread{background:#f2f6ef}.ep-notice-item b{display:block;font-size:13px}.ep-notice-item p{margin:5px 0 0;color:#6f7871;font-size:12px;line-height:1.5}.ep-notice-item time{display:block;margin-top:6px;color:#9aa19c;font-size:10px}.ep-notice-empty{padding:38px 20px;text-align:center;color:#7b847d}`;document.head.appendChild(s)}
async function getSession(){return (await sb.auth.getSession()).data.session}
async function load(){const s=await getSession();if(!s)return;const {data,error}=await sb.from('notifications').select('id,type,title,body,subject_id,library_item_id,read_at,created_at').eq('user_id',s.user.id).order('created_at',{ascending:false}).limit(30);if(error)return;items=data||[];paint()}
function mount(){const head=document.querySelector('.head-actions');if(!head||document.getElementById('epNoticeWrap'))return;style();const wrap=document.createElement('div');wrap.id='epNoticeWrap';wrap.className='ep-notice-wrap';wrap.innerHTML=`<button class="ep-notice-btn" id="epNoticeBtn" aria-label="通知">铃 <span class="ep-notice-badge" id="epNoticeBadge" style="display:none">0</span></button><div class="ep-notice-panel" id="epNoticePanel" style="display:none"><div class="ep-notice-head"><b>通知</b><button class="mini" id="epNoticeReadAll">全部已读</button></div><div id="epNoticeList"></div></div>`;head.insertBefore(wrap,head.firstElementChild);wrap.querySelector('#epNoticeBtn').onclick=e=>{e.stopPropagation();open=!open;wrap.querySelector('#epNoticePanel').style.display=open?'block':'none';if(open)load()};wrap.querySelector('#epNoticeReadAll').onclick=async()=>{const s=await getSession();if(!s)return;await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',s.user.id).is('read_at',null);load()};document.addEventListener('click',e=>{if(!wrap.contains(e.target)){open=false;wrap.querySelector('#epNoticePanel').style.display='none'}});load()}
function paint(){const list=document.getElementById('epNoticeList'),badge=document.getElementById('epNoticeBadge');if(!list)return;const unread=items.filter(x=>!x.read_at).length;badge.textContent=unread>99?'99+':String(unread);badge.style.display=unread?'grid':'none';list.innerHTML=items.length?items.map(x=>`<div class="ep-notice-item ${x.read_at?'':'unread'}" data-notice-id="${esc(x.id)}"><b>${esc(x.title)}</b><p>${esc(x.body||'')}</p><time>${new Date(x.created_at).toLocaleString('zh-CN')}</time></div>`).join(''):`<div class="ep-notice-empty">暂无新通知</div>`;list.querySelectorAll('[data-notice-id]').forEach(el=>el.onclick=async()=>{const id=el.dataset.noticeId;await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);const n=items.find(x=>x.id===id);if(n?.type==='resource_review')location.href='admin.html';else load()})}
const mo=new MutationObserver(()=>setTimeout(mount,100));mo.observe(document.body,{childList:true,subtree:true});setTimeout(mount,500);setInterval(load,15000);