-- ============================================================
-- Episteme 知屿 — Supabase database setup
-- Run this entire file in Supabase Dashboard → SQL Editor.
-- ============================================================

create extension if not exists pgcrypto;

-- ---------- profiles ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default 'New member',
  avatar_url text,
  grade text,
  bio text,
  role text not null default 'student' check (role in ('student','subject_manager','admin')),
  created_at timestamptz not null default now()
);

-- ---------- subjects ----------
create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text,
  description text,
  created_at timestamptz not null default now()
);

-- ---------- questions ----------
create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete set null,
  topic text,
  title text not null,
  content text not null,
  status text not null default 'unanswered' check (status in ('unanswered','discussing','answered','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- answers ----------
create table if not exists public.answers (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.questions(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  is_verified boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------- courses ----------
create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  subject_id bigint references public.subjects(id) on delete set null,
  teacher_id uuid references public.profiles(id) on delete set null,
  thumbnail_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.course_lessons (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(id) on delete cascade,
  title text not null,
  video_url text,
  duration_seconds integer default 0,
  lesson_order integer not null default 0
);

-- ---------- resources ----------
create table if not exists public.resources (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  subject_id bigint references public.subjects(id) on delete set null,
  topic text,
  resource_type text not null default 'note' check (resource_type in ('note','paper','handout','tool','other')),
  file_path text,
  external_url text,
  uploader_id uuid references public.profiles(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

-- ---------- knowledge base ----------
create table if not exists public.knowledge_base (
  id uuid primary key default gen_random_uuid(),
  question_id uuid references public.questions(id) on delete set null,
  title text not null,
  summary text,
  subject_id bigint references public.subjects(id) on delete set null,
  topic text,
  created_at timestamptz not null default now()
);

-- ---------- real-time community messages ----------
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  channel text not null,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists questions_created_at_idx on public.questions(created_at desc);
create index if not exists questions_subject_idx on public.questions(subject_id);
create index if not exists answers_question_idx on public.answers(question_id);
create index if not exists messages_channel_created_idx on public.messages(channel, created_at desc);
create index if not exists resources_subject_idx on public.resources(subject_id);

-- ---------- updated_at trigger ----------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists questions_updated_at on public.questions;
create trigger questions_updated_at before update on public.questions
for each row execute function public.set_updated_at();

-- ---------- automatically create profile on signup ----------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(coalesce(new.email,''),'@',1), 'New member'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ---------- seed subjects ----------
insert into public.subjects (name,code,description) values
('Mathematics','0606','IGCSE Additional Mathematics'),
('Mathematics','0580','IGCSE Mathematics'),
('Physics','0625','IGCSE Physics'),
('Chemistry','0620','IGCSE Chemistry'),
('Biology','0610','IGCSE Biology'),
('English','0500 / 0475','English / Literature'),
('Economics','0455','IGCSE Economics'),
('Geography','IG','Geography'),
('History','AQA','History'),
('Theatre & Arts','IG','Theatre / Arts'),
('Music','ABRSM','Music')
on conflict (name) do nothing;

-- ---------- RLS ----------
alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.questions enable row level security;
alter table public.answers enable row level security;
alter table public.courses enable row level security;
alter table public.course_lessons enable row level security;
alter table public.resources enable row level security;
alter table public.knowledge_base enable row level security;
alter table public.messages enable row level security;

-- Helper: current role
create or replace function public.my_role()
returns text language sql stable security definer set search_path=public
as $$ select role from public.profiles where id = auth.uid() $$;

-- profiles
drop policy if exists "profiles readable by authenticated" on public.profiles;
create policy "profiles readable by authenticated" on public.profiles for select to authenticated using (true);
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());

-- subjects
drop policy if exists "subjects public read" on public.subjects;
create policy "subjects public read" on public.subjects for select using (true);

-- questions
drop policy if exists "questions public read" on public.questions;
create policy "questions public read" on public.questions for select using (true);
drop policy if exists "authenticated create questions" on public.questions;
create policy "authenticated create questions" on public.questions for insert to authenticated with check (author_id=auth.uid());
drop policy if exists "author or manager update questions" on public.questions;
create policy "author or manager update questions" on public.questions for update to authenticated
using (author_id=auth.uid() or public.my_role() in ('subject_manager','admin'))
with check (author_id=auth.uid() or public.my_role() in ('subject_manager','admin'));
drop policy if exists "author or admin delete questions" on public.questions;
create policy "author or admin delete questions" on public.questions for delete to authenticated
using (author_id=auth.uid() or public.my_role()='admin');

-- answers
drop policy if exists "answers public read" on public.answers;
create policy "answers public read" on public.answers for select using (true);
drop policy if exists "authenticated create answers" on public.answers;
create policy "authenticated create answers" on public.answers for insert to authenticated with check (author_id=auth.uid());
drop policy if exists "answer author or manager update" on public.answers;
create policy "answer author or manager update" on public.answers for update to authenticated
using (author_id=auth.uid() or public.my_role() in ('subject_manager','admin'))
with check (author_id=auth.uid() or public.my_role() in ('subject_manager','admin'));

-- courses
drop policy if exists "courses public read" on public.courses;
create policy "courses public read" on public.courses for select using (true);
drop policy if exists "managers create courses" on public.courses;
create policy "managers create courses" on public.courses for insert to authenticated with check (public.my_role() in ('subject_manager','admin'));
drop policy if exists "managers update courses" on public.courses;
create policy "managers update courses" on public.courses for update to authenticated using (public.my_role() in ('subject_manager','admin')) with check (public.my_role() in ('subject_manager','admin'));

-- lessons
drop policy if exists "lessons public read" on public.course_lessons;
create policy "lessons public read" on public.course_lessons for select using (true);
drop policy if exists "managers manage lessons" on public.course_lessons;
create policy "managers manage lessons" on public.course_lessons for all to authenticated using (public.my_role() in ('subject_manager','admin')) with check (public.my_role() in ('subject_manager','admin'));

-- resources
drop policy if exists "approved resources public read" on public.resources;
create policy "approved resources public read" on public.resources for select using (status='approved' or uploader_id=auth.uid() or public.my_role() in ('subject_manager','admin'));
drop policy if exists "authenticated upload resources" on public.resources;
create policy "authenticated upload resources" on public.resources for insert to authenticated with check (uploader_id=auth.uid());
drop policy if exists "uploader or manager update resources" on public.resources;
create policy "uploader or manager update resources" on public.resources for update to authenticated
using (uploader_id=auth.uid() or public.my_role() in ('subject_manager','admin'))
with check (uploader_id=auth.uid() or public.my_role() in ('subject_manager','admin'));

-- KB
drop policy if exists "kb public read" on public.knowledge_base;
create policy "kb public read" on public.knowledge_base for select using (true);
drop policy if exists "managers manage kb" on public.knowledge_base;
create policy "managers manage kb" on public.knowledge_base for all to authenticated using (public.my_role() in ('subject_manager','admin')) with check (public.my_role() in ('subject_manager','admin'));

-- messages
drop policy if exists "messages authenticated read" on public.messages;
create policy "messages authenticated read" on public.messages for select to authenticated using (true);
drop policy if exists "messages authenticated insert own" on public.messages;
create policy "messages authenticated insert own" on public.messages for insert to authenticated with check (author_id=auth.uid());

-- ---------- Storage ----------
insert into storage.buckets (id,name,public) values ('episteme-resources','episteme-resources',true)
on conflict (id) do nothing;

drop policy if exists "public read episteme resources" on storage.objects;
create policy "public read episteme resources" on storage.objects for select using (bucket_id='episteme-resources');

drop policy if exists "authenticated upload episteme resources" on storage.objects;
create policy "authenticated upload episteme resources" on storage.objects for insert to authenticated
with check (bucket_id='episteme-resources');

drop policy if exists "owner delete episteme resources" on storage.objects;
create policy "owner delete episteme resources" on storage.objects for delete to authenticated
using (bucket_id='episteme-resources' and owner_id=auth.uid());

-- ---------- Realtime ----------
do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.questions;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.answers;
exception when duplicate_object then null;
end $$;

-- ============================================================
-- AFTER RUNNING THIS:
-- 1. Create your first account in the website.
-- 2. In Supabase SQL Editor run:
--
-- update public.profiles
-- set role='admin'
-- where id=(select id from auth.users order by created_at asc limit 1);
--
-- This makes the first account the site admin.
-- ============================================================
