import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{};const sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);
let currentUser=null,currentProfile=null,currentCourses=[],currentLessons=[],mounted=false;
const esc=s=>String(s??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const isCoordinator=()=>currentProfile?.role==="coordinator";
async function loadData(){const {data:{session}}=await sb.auth.getSession();if(!session)return false;currentUser=session.user;const p=await sb.from("profiles").select("id,username,role").eq("id",currentUser.id).maybeSingle();currentProfile=p.data||null;if(!currentProfile||!["coordinator","subject_manager"].includes(currentProfile.role))return false;const [cr,lr,mr]=await Promise.all([sb.from("courses").select("id,title,description,subject_id,course_type,status,is_hidden,subjects(name)").order("created_at",{ascending:false}),sb.from("course_lessons").select("id,course_id,title,description,video_url,video_provider,video_ref,duration_seconds,lesson_order,storage_path").order("lesson_order"),sb.from("subject_managers").select("user_id,subject_id")]);if(cr.error)throw cr.error;if(lr.error)throw lr.error;if(mr.error)throw mr.error;const ids=new Set((mr.data||[]).filter(x=>x.user_id===currentUser.id).map(x=>Number(x.subject_id)));currentCourses=isCoordinator()?(cr.data||[]):(cr.data||[]).filter(x=>ids.has(Number(x.subject_id)));currentLessons=lr.data||[];return true}
function fmtDuration(n){n=Number(n||0);if(!n)return "视频课";const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=Math.floor(n%60);return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${m}:${String(s).padStart(2,"0")}`}
function getBv(v){return (String(v||"").match(/BV[0-9A-Za-z]+/)||[])[0]||""}
function lessonPanel(){const options=currentCourses.map(c=>`<option value="${esc(c.id)}">${esc(c.title)} · ${esc(c.subjects?.name||"未分类")}</option>`).join("");return `<div class="admin-card" id="storageLessonPanel" style="margin-top:20px"><h2>视频课管理</h2><div class="section-note">视频统一使用 Bilibili。这里不上传视频文件，只保存课程需要的播放信息；视频本体不会进入网站存储。</div>${currentCourses.length?`<form id="lessonUploadForm" class="form-grid"><label>课程<select name="course_id" required>${options}</select></label><label>Lesson 标题<input name="title" required placeholder="例如：Chapter 1 · Atomic Structure"></label><label>Lesson 简介<textarea name="description" placeholder="可选"></textarea></label><label>Bilibili 视频链接或 BV 号<input name="video" required placeholder="粘贴 Bilibili 视频链接或 BV 号"></label><label>视频时长（秒）<input name="duration" type="number" min="0" step="1" placeholder="可选"></label><button class="primary" type="submit" id="lessonUploadBtn">添加视频课</button><div id="lessonUploadStatus" class="muted" style="font-size:13px"></div></form>`:`<div class="empty-admin">请先创建课程，再添加 Lesson 视频课。</div>`}<div style="height:22px"></div><h3 style="margin:0 0 12px">已添加视频课</h3><div class="manager-list" id="lessonList">${renderRows()}</div></div>`}
function renderRows(){if(!currentLessons.length)return `<div class="empty-admin">暂无视频课</div>`;const map=new Map(currentCourses.map(c=>[c.id,c]));const rows=currentLessons.filter(l=>map.has(l.course_id));if(!rows.length)return `<div class="empty-admin">暂无属于你可管理课程的视频课</div>`;return rows.map(l=>{const c=map.get(l.course_id);const bv=getBv(l.video_ref||l.video_url);return `<div class="manager-row"><div style="min-width:0"><b>${esc(l.title)}</b><small>${esc(c.title)} · ${esc(c.subjects?.name||"未分类")} · ${fmtDuration(l.duration_seconds)}${bv?` · ${esc(bv)}`:""}</small></div><div class="admin-actions"><button class="mini" data-lesson-view="${esc(l.id)}">预览</button><button class="mini danger" data-lesson-delete="${esc(l.id)}">删除</button></div></div>`}).join("")}
async function addLesson(e){e.preventDefault();const form=e.currentTarget,btn=document.getElementById("lessonUploadBtn"),status=document.getElementById("lessonUploadStatus"),fd=new FormData(form),courseId=String(fd.get("course_id")||""),title=String(fd.get("title")||"").trim(),description=String(fd.get("description")||"").trim(),video=String(fd.get("video")||"").trim(),duration=Math.max(0,Number(fd.get("duration")||0)||0),course=currentCourses.find(c=>c.id===courseId),bv=getBv(video);if(!course)return alert("请选择有效课程。");if(!bv)return alert("请输入有效的 Bilibili 视频链接或 BV 号。");btn.disabled=true;status.textContent="正在保存视频课……";try{const order=currentLessons.filter(l=>l.course_id===course.id).reduce((m,l)=>Math.max(m,Number(l.lesson_order||0)),-1)+1;const r=await sb.from("course_lessons").insert({course_id:course.id,title,description:description||null,duration_seconds:duration,lesson_order:order,video_provider:"bilibili",video_ref:bv,video_url:video,storage_path:null});if(r.error)throw r.error;form.reset();status.textContent="添加完成。";await refreshPanel()}catch(err){status.textContent="保存失败。";alert(`添加失败：${err?.message||err}`)}finally{btn.disabled=false}}
function viewLesson(id){const l=currentLessons.find(x=>x.id===id);if(!l)return;const bv=getBv(l.video_ref||l.video_url);if(!bv)return;window.open(`https://www.bilibili.com/video/${encodeURIComponent(bv)}`,"_blank","noopener,noreferrer")}
async function deleteLesson(id){const l=currentLessons.find(x=>x.id===id);if(!l)return;if(!confirm(`确定删除视频课「${l.title}」？`))return;const r=await sb.from("course_lessons").delete().eq("id",id);if(r.error)return alert(`删除失败：${r.error.message}`);await refreshPanel()}
async function refreshPanel(){await loadData();const old=document.getElementById("storageLessonPanel");if(!old)return;const w=document.createElement("div");w.innerHTML=lessonPanel();old.replaceWith(w.firstElementChild);bind()}
function bind(){document.getElementById("lessonUploadForm")?.addEventListener("submit",addLesson);document.querySelectorAll("[data-lesson-view]").forEach(b=>b.addEventListener("click",()=>viewLesson(b.dataset.lessonView)));document.querySelectorAll("[data-lesson-delete]").forEach(b=>b.addEventListener("click",()=>deleteLesson(b.dataset.lessonDelete)))}
async function mount(){if(mounted||!document.querySelector("#view .admin-table"))return;const heading=document.querySelector("#view .admin-card h2");if(!heading||heading.textContent.trim()!=="现有录课")return;try{if(!await loadData())return;if(document.getElementById("storageLessonPanel"))return;document.querySelector("#view")?.insertAdjacentHTML("beforeend",lessonPanel());bind();mounted=true}catch(e){console.error("Video course panel init failed",e)}}
new MutationObserver(()=>{mounted=false;mount()}).observe(document.body,{childList:true,subtree:true});setTimeout(mount,500);sb.auth.onAuthStateChange(()=>{mounted=false;setTimeout(mount,300)});
