import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{},sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY),$=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
let subjects=[],managers=[],me,profile;
const toast=m=>{const t=$("#toast");if(t){t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}};
const css=`.video-admin-upload{margin-bottom:12px;padding:16px;border:1px solid var(--line);border-radius:20px;background:#fff}.video-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.video-admin-grid input,.video-admin-grid select,.video-admin-grid textarea{width:100%;box-sizing:border-box;border:1px solid #dfe5dc;border-radius:8px;padding:9px 10px;background:#fff;font:inherit;font-size:12px}.video-admin-grid textarea{min-height:65px;resize:vertical}.video-admin-full{grid-column:1/-1}.video-admin-upload button{border:0;border-radius:8px;padding:9px 14px;background:#1f2923;color:#fff;cursor:pointer}.video-admin-note{margin-top:10px;color:#737b75;font-size:11px;line-height:1.6}.video-admin-player{width:min(100%,900px);aspect-ratio:16/9;background:#111;border-radius:12px;overflow:hidden}.video-admin-player iframe{width:100%;height:100%;border:0}.video-admin-actions{display:flex;gap:5px;margin-top:9px}.video-admin-actions button{border:1px solid #e5e9e3;background:#fff;border-radius:8px;padding:7px 10px;font-size:11px;cursor:pointer}.video-admin-actions .ok{background:#e7efdf}.video-admin-actions .no{background:#f3e8e8}.video-admin-status{margin-left:auto;padding:5px 8px;border-radius:999px;font-size:10px;background:#f7f0d9}.video-admin-status.approved{background:#e7efdf}.video-admin-status.rejected{background:#f3e8e8}@media(max-width:720px){.video-admin-grid{grid-template-columns:1fr}.video-admin-full{grid-column:auto}}`;
function injectStyle(){if($("#video-admin-style"))return;const s=document.createElement("style");s.id="video-admin-style";s.textContent=css;document.head.appendChild(s)}
function bv(v){return(v||"").match(/BV[0-9A-Za-z]+/)?.[0]||""}
async function load(){const[s,m,p]=await Promise.all([sb.from("subjects").select("id,name,code").order("name"),sb.from("subject_managers").select("user_id,subject_id"),sb.from("profiles").select("id,username,role").eq("id",me.id).single()]);if(s.error||m.error||p.error)throw(s.error||m.error||p.error);subjects=s.data||[];managers=m.data||[];profile=p.data}
function allowedSubjects(){if(profile.role==="coordinator")return subjects;const ids=new Set(managers.filter(x=>x.user_id===me.id).map(x=>Number(x.subject_id)));return subjects.filter(x=>ids.has(Number(x.id)))}
async function courses(){const{data,error}=await sb.from("courses").select("id,title,description,subject_id,teacher_id,course_type,status,is_hidden,created_at,profiles:teacher_id(username)").order("created_at",{ascending:false});if(error)throw error;const ids=new Set(allowedSubjects().map(x=>Number(x.id)));const cs=(data||[]).filter(c=>ids.has(Number(c.subject_id)));const{data:ls,error:le}=await sb.from("course_lessons").select("id,course_id,title,video_url,video_provider,video_ref,duration_seconds").eq("video_provider","bilibili");if(le)throw le;return{cs:cs.filter(c=>(ls||[]).some(l=>l.course_id===c.id)),ls:ls||[]}}
function subjectName(id){return subjects.find(s=>Number(s.id)===Number(id))?.name||"未分类"}
function status(c){return c.status==="published"?"approved":c.status==="archived"?"rejected":"pending"}
function statusText(s){return s==="approved"?"已通过":s==="rejected"?"已驳回":"待审核"}
function player(l){const b=bv(l?.video_ref||l?.video_url);return b?`<div class="video-admin-player"><iframe src="https://player.bilibili.com/player.html?bvid=${encodeURIComponent(b)}&autoplay=0&danmaku=1" allowfullscreen referrerpolicy="no-referrer-when-downgrade"></iframe></div>`:`<div class="reader-empty"><b>无法识别 Bilibili BV 号</b></div>`}
async function render(){injectStyle();const{cs,ls}=await courses();const tab=document.querySelector("[data-video-admin-tab]");if(!tab)return;const wrap=document.createElement("div");wrap.id="videoAdminView";wrap.innerHTML=`<section class="video-admin-upload"><div class="section-label">UPLOAD VIDEO</div><h3 style="margin:5px 0">提交 Bilibili 视频</h3><p style="margin:0 0 12px;color:var(--muted);font-size:12px">先在 Bilibili 上传视频并保持非公开，再把链接提交到这里。提交后网站不会公开，审核通过后才会公开。</p><div class="video-admin-grid"><input id="vaTitle" placeholder="视频标题"><input id="vaLesson" placeholder="章节标题"><select id="vaSubject"><option value="">选择学科</option>${allowedSubjects().map(s=>`<option value="${s.id}">${esc(s.name)}${s.code?` · ${esc(s.code)}`:""}</option>`).join("")}</select><select id="vaType"><option value="textbook">Textbook Content</option><option value="ig">IGCSE Question Walkthrough</option><option value="advanced">Extension & Topics</option></select><input class="video-admin-full" id="vaUrl" placeholder="Bilibili 视频链接或 BV 号"><textarea class="video-admin-full" id="vaDesc" placeholder="课程简介"></textarea><button class="video-admin-full" id="vaSubmit">提交审核</button></div><div class="video-admin-note">审核通过后，Episteme 会把课程从隐藏状态切换为公开。Bilibili 的公开状态不能仅通过普通视频链接由网站后台代为切换；如果要做到“审核通过后自动把 Bilibili 也公开”，还需要接入 Bilibili 官方账号/API 授权。</div></section><div class="audit"><section class="review-list"><div class="list-head"><b>视频审核</b><span>${cs.length} 个视频 · 左侧选择，右侧播放器预览</span></div>${cs.length?cs.map(c=>{const l=ls.find(x=>x.course_id===c.id),st=status(c);return`<article class="review-item" data-va-id="${c.id}"><button class="item-main" data-va-select="${c.id}"><strong>${esc(c.title)}</strong><small>${esc(subjectName(c.subject_id))} · ${esc(c.profiles?.username||"成员")}</small><em>${esc(l?.video_ref||"Bilibili")}</em></button><div class="video-admin-actions"><button class="ok" data-va-review="published" data-id="${c.id}">通过</button><button data-va-review="draft" data-id="${c.id}">重审</button><button class="no" data-va-review="archived" data-id="${c.id}">驳回</button><span class="video-admin-status ${st}">${statusText(st)}</span></div></article>`}).join(""):"<div class=\"empty-list\">暂无视频</div>"}</section><section class="audit-right" id="videoAdminPane"><div class="reader-empty"><b>选择一个视频</b><span>审核时直接使用 Bilibili 播放器预览</span></div></section></div>`;const root=$("#view");root.innerHTML="";root.appendChild(wrap);$("#vaSubmit").onclick=submit;document.querySelectorAll("[data-va-select]").forEach(x=>x.onclick=()=>select(x.dataset.vaSelect));document.querySelectorAll("[data-va-review]").forEach(x=>x.onclick=()=>review(x.dataset.id,x.dataset.vaReview))}
async function select(id){const{cs,ls}=await courses(),c=cs.find(x=>x.id===id),l=ls.find(x=>x.course_id===id),p=$("#videoAdminPane");if(!c||!l)return;p.innerHTML=`<div class="reader-head"><div><b>${esc(c.title)}</b><small>${esc(subjectName(c.subject_id))} · ${esc(c.profiles?.username||"成员")} · ${esc(l.video_ref||"")}</small></div><span class="status ${status(c)}">${statusText(status(c))}</span></div><div class="reader-body">${player(l)}</div><div class="review-note">网站状态：${statusText(status(c))}。审核前保持隐藏，审核通过后网站公开。</div>`;document.querySelectorAll("[data-va-id]").forEach(x=>x.classList.toggle("active",x.dataset.vaId===id))}
async function submit(){const title=$("#vaTitle")?.value.trim(),lesson=$("#vaLesson")?.value.trim(),subject=$("#vaSubject")?.value,type=$("#vaType")?.value,url=$("#vaUrl")?.value.trim(),desc=$("#vaDesc")?.value.trim();if(!title||!subject||!url)return toast("请填写标题、学科和 Bilibili 链接");const r=await sb.rpc("submit_bilibili_course",{p_title:title,p_description:desc,p_subject_id:Number(subject),p_course_type:type,p_lesson_title:lesson,p_bilibili_url:url});if(r.error)return toast(r.error.message||"提交失败");toast("已提交，网站保持隐藏，等待审核");await render()}
async function review(id,status){const r=await sb.rpc("review_bilibili_course",{p_course_id:id,p_status:status});if(r.error)return toast(r.error.message||"操作失败");toast(status==="published"?"已通过，网站已公开":status==="archived"?"已驳回":"已放回重审");await render()}
function mount(){const tabs=$(".admin-tabs");if(!tabs||tabs.querySelector("[data-video-admin-tab]"))return;const b=document.createElement("button");b.className="admin-tab";b.dataset.videoAdminTab="1";b.textContent="视频审核";tabs.appendChild(b);b.onclick=async()=>{tabs.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");await render()}}
(async()=>{try{const{data:{session}}=await sb.auth.getSession();if(!session)return;me=session.user;await load();const mo=new MutationObserver(()=>{if($(".admin-tabs")){mount();mo.disconnect()}});mo.observe(document.body,{childList:true,subtree:true});mount()}catch(e){console.error(e)}})();
