import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.EPISTEME_CONFIG||{},sb=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY),$=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
let me,profile,subjects=[],managers=[];
const toast=m=>{const t=$("#toast");if(t){t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}};
const css=`.video-portal{max-width:860px;margin:0 auto}.video-portal-card{padding:22px;border:1px solid var(--line,#e5e9e3);border-radius:18px;background:#fff}.video-portal-card h2{margin:5px 0 7px;font-size:20px}.video-portal-card p{margin:0 0 18px;color:var(--muted,#737b75);font-size:12px;line-height:1.7}.video-portal-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.video-portal-grid input,.video-portal-grid select,.video-portal-grid textarea{width:100%;box-sizing:border-box;border:1px solid #dfe5dc;border-radius:9px;padding:10px 11px;background:#fff;font:inherit;font-size:12px}.video-portal-grid textarea{min-height:78px;resize:vertical}.video-portal-full{grid-column:1/-1}.video-portal-submit{border:0;border-radius:9px;padding:10px 15px;background:#1f2923;color:#fff;cursor:pointer;font-weight:600}.video-portal-note{margin-top:14px;padding:11px 12px;border-radius:10px;background:#f7f8f4;color:#737b75;font-size:11px;line-height:1.6}.video-portal-success{margin-top:12px;padding:10px 12px;border-radius:9px;background:#e7efdf;color:#40513e;font-size:12px;display:none}@media(max-width:720px){.video-portal-grid{grid-template-columns:1fr}.video-portal-full{grid-column:auto}}`;
function injectStyle(){if($("#video-portal-style"))return;const s=document.createElement("style");s.id="video-portal-style";s.textContent=css;document.head.appendChild(s)}
async function load(){const[s,m,p]=await Promise.all([sb.from("subjects").select("id,name,code").order("name"),sb.from("subject_managers").select("user_id,subject_id"),sb.from("profiles").select("id,username,role").eq("id",me.id).single()]);if(s.error||m.error||p.error)throw(s.error||m.error||p.error);subjects=s.data||[];managers=m.data||[];profile=p.data}
function allowedSubjects(){if(profile.role==="coordinator")return subjects;const ids=new Set(managers.filter(x=>x.user_id===me.id).map(x=>Number(x.subject_id)));return subjects.filter(x=>ids.has(Number(x.id)))}
function mount(){const tabs=$(".admin-tabs");if(!tabs||tabs.querySelector("[data-video-portal-tab]"))return;const b=document.createElement("button");b.className="admin-tab";b.dataset.videoPortalTab="1";b.textContent="上传视频";tabs.appendChild(b);b.onclick=()=>{tabs.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()}}
function render(){injectStyle();const subs=allowedSubjects();const root=$("#view");if(!root)return;root.innerHTML=`<div class="video-portal"><section class="video-portal-card"><div class="section-label">VIDEO PORTAL</div><h2>上传 Bilibili 视频</h2><p>这里只提交已经上传到 Bilibili 的视频链接。提交后，视频会先以“待审核 + 网站隐藏”的状态进入 Episteme；审核通过后，才会在网站公开。</p><div class="video-portal-grid"><input id="vpTitle" placeholder="视频标题"><input id="vpLesson" placeholder="章节标题（可选）"><select id="vpSubject"><option value="">选择学科</option>${subs.map(s=>`<option value="${s.id}">${esc(s.name)}${s.code?` · ${esc(s.code)}`:""}</option>`).join("")}</select><select id="vpType"><option value="textbook">Textbook Content</option><option value="ig">IGCSE Question Walkthrough</option><option value="advanced">Extension & Topics</option></select><input class="video-portal-full" id="vpUrl" placeholder="粘贴 Bilibili 视频链接或 BV 号"><textarea class="video-portal-full" id="vpDesc" placeholder="课程简介（可选）"></textarea><button class="video-portal-full video-portal-submit" id="vpSubmit">提交审核</button></div><div class="video-portal-note">网站端不会在提交时公开视频。审核人会在“视频审核”里审核；通过后，Episteme 才会显示该视频。</div><div class="video-portal-success" id="vpSuccess">提交成功。视频目前处于待审核状态，网站端已隐藏。</div></section></div>`;$("#vpSubmit").onclick=submit}
async function submit(){const title=$("#vpTitle")?.value.trim(),lesson=$("#vpLesson")?.value.trim(),subject=$("#vpSubject")?.value,type=$("#vpType")?.value,url=$("#vpUrl")?.value.trim(),desc=$("#vpDesc")?.value.trim();if(!title||!subject||!url)return toast("请填写视频标题、学科和 Bilibili 链接");const btn=$("#vpSubmit");btn.disabled=true;btn.textContent="提交中…";try{const r=await sb.rpc("submit_bilibili_course",{p_title:title,p_description:desc,p_subject_id:Number(subject),p_course_type:type,p_lesson_title:lesson,p_bilibili_url:url});if(r.error)throw r.error;$("#vpSuccess").style.display="block";toast("已提交，网站暂时隐藏");["#vpTitle","#vpLesson","#vpUrl","#vpDesc"].forEach(s=>{const x=$(s);if(x)x.value=""});$("#vpSubject").value=""}catch(e){toast(e.message||"提交失败")}finally{btn.disabled=false;btn.textContent="提交审核"}}
(async()=>{try{const{data:{session}}=await sb.auth.getSession();if(!session)return;me=session.user;await load();const mo=new MutationObserver(()=>mount());mo.observe(document.body,{childList:true,subtree:true});mount()}catch(e){console.error(e)}})();